### ISSUE TITLE
minikube 1.23: Your cgroup does not allow setting memory

### ISSUE THREAD

**Issue by cmanzur** [kubernetes/minikube#12842]
**Steps to reproduce the issue:** 

1. `minikube start --memory=8192 --cpus 2 --kubernetes-version=v1.22.1`
```
😄  minikube v1.23.2 on Ubuntu 20.04
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=8192MB) ...
🐳  Preparing Kubernetes v1.22.1 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

- minikube 1.23.2
- docker 20.10.5
- ubuntu 20.04.2

```
docker stats

CONTAINER ID   NAME       CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O    PIDS
4ec4a910c4e5   minikube   14.05%    573.4MiB / 62.74GiB   0.89%     191kB / 294kB   0B / 229kB   323
```

As you can see, there's NO memory limit.

```
grep GRUB_CMDLINE_LINUX /etc/default/grub

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"
```
Of course, I run `sudo update-grub2` without errors and reboot the PC.

**Comment by medyagh** [comment]
@cmanzur this is a limitation of your ubuntu's cgroups as minikube detected and informed you 

```
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities

```

did you already read the link that minikube suggested to read?

**Comment by cmanzur** [comment]
@medyagh I already read that.

But If I run:
```
docker run -it -m 8m --rm nginx

CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O     PIDS
32273ec91d5d   dazzling_kare   0.00%     6.875MiB / 8MiB       85.94%    3.65kB / 0B     0B / 16.4kB   9
4ec4a910c4e5   minikube        15.70%    586.3MiB / 62.74GiB   0.91%     212kB / 294kB   0B / 229kB    324
```

You can notice the nginx container has the limit, so it's a minikube stuff, not docker / cgroups related.

**Comment by miroslav-beranic** [comment]
Hi all,

just landed on this issue, as I was looking to resolve my issue on Fedora 35.
```
$ minikube start --nodes 2 -p  demo --cpus 4 --memory 8196
😄  [demo] minikube v1.24.0 on Fedora 35
✨  Using the podman driver based on user configuration
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node demo in cluster demo
🚜  Pulling base image ...
.
.
.
```

Current Fedora with latest updates, Minikube built from github master ( 1 day ago ). In all messages it is written, this is related to Ubuntu's limitations, but I have Fedora 35 only system setup. I did not notice it in my first run. When doing different setup:

```
minikube start
😄  minikube v1.24.0 on Fedora 35
✨  Using the podman driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.22.4 preload ...
```

It seems ( for me ) only reported, when using multi-node setup. I've tried it with cri-o and containerd, both with same results ( ie. error reported ).

Non-related difference between Ubuntu 20.04 LTS install and Fedora 35 install is, that on Fedora 35 error is reported:
```
E1128 09:45:11.741938  121883 cache.go:201] Error downloading kic artifacts:  not yet implemented, see issue #8426
```
This error is reported regardless of using cri-o or containerd.

On Ubuntu 20.04 LTS this error ( E1128 ) is reported when using cio-o, but not reported when using containerd. All packages of same versions - built from github master.

**Comment by kscherer** [comment]
I am running Ubuntu 21.10 and I also see this message when running `minikube start --cpus max --memory 8g` even though /proc/cmdline shows the relevant options are enabled. I read through the source and minikube is looking for "/sys/fs/cgroup/memory/memory.swap.max" which doesn't exist on my system. My system is using cgroup v2 and the memory controller is enabled.
```
> mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
> systemd --version
systemd 248 (248.3-1ubuntu8)
+PAM <snip> default-hierarchy=unified
> cat /sys/fs/cgroup/cgroup.controllers
cpuset cpu io memory hugetlb pids rdma misc
> cat /sys/fs/cgroup/cgroup.subtree_control
cpuset cpu io memory hugetlb pids rdma misc
```
Hopefully someone more familiar with cgroups v1 and v2 can suggest a better test

**Comment by fastlorenzo** [comment]
Same here with Ubuntu 20.04

```
$ minikube start --driver=docker --nodes=2 --cpus=3 --memory='12g'
😄  minikube v1.24.0 on Ubuntu 20.04
✨  Using the docker driver based on user configuration
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=3, Memory=12288MB) ...
🐳  Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

👍  Starting worker node minikube-m02 in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=3, Memory=12288MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.49.2
🐳  Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
    ▪ env NO_PROXY=192.168.49.2
🔎  Verifying Kubernetes components...
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
$ uname -a
Linux ns3041971 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
$ docker info | grep -i cgroup
 Cgroup Driver: systemd
 Cgroup Version: 2
  cgroupns
$ fgrep GRUB_CMD /etc/default/grub
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=1 cgroup_enable=memory swapaccount=1 vga=normal nomodeset iommu=pt"
```

Docker is supporting memory limit. I did a quick test:

```
$ docker run -it -m 200m --rm -d nginx
7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a
$ docker stats --no-stream -a
CONTAINER ID   NAME              CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O     PIDS
7a0c2a2061ed   trusting_shtern   0.00%     17MiB / 200MiB        8.50%     946B / 0B         0B / 36.9kB   17
29230f1ebf3c   minikube-m02      15.49%    246.7MiB / 62.49GiB   0.39%     55.9MB / 1.19MB   0B / 3.39MB   151
e4c32fcecf51   minikube          12.30%    677.7MiB / 62.49GiB   1.06%     55.5MB / 1.7MB    0B / 61.4kB   415
```

It looks like the check in Minikube to validate if memory cgroup is enabled is not reliable (https://github.com/kubernetes/minikube/blob/25d17c2dde4920c00b4fe6f42aece999ce92cd5c/pkg/drivers/kic/oci/oci.go#L111-L124).

```
$ ls /sys/fs/cgroup/memory/memsw.limit_in_bytes
ls: cannot access '/sys/fs/cgroup/memory/memsw.limit_in_bytes': No such file or directory
```

Some additional info if it helps:

```
$ ls -l /sys/fs/cgroup/
total 0
-r--r--r--  1 root root 0 Dec 27 22:26 cgroup.controllers
-rw-r--r--  1 root root 0 Dec 27 22:27 cgroup.max.depth
-rw-r--r--  1 root root 0 Dec 27 22:27 cgroup.max.descendants
-rw-r--r--  1 root root 0 Dec 27 22:26 cgroup.procs
-r--r--r--  1 root root 0 Dec 27 22:27 cgroup.stat
-rw-r--r--  1 root root 0 Dec 27 22:26 cgroup.subtree_control
-rw-r--r--  1 root root 0 Dec 27 22:27 cgroup.threads
-rw-r--r--  1 root root 0 Dec 27 22:27 cpu.pressure
-r--r--r--  1 root root 0 Dec 27 22:27 cpuset.cpus.effective
-r--r--r--  1 root root 0 Dec 27 22:27 cpuset.mems.effective
drwxr-xr-x  2 root root 0 Dec 27 22:26 init.scope
-rw-r--r--  1 root root 0 Dec 27 22:27 io.cost.model
-rw-r--r--  1 root root 0 Dec 27 22:27 io.cost.qos
-rw-r--r--  1 root root 0 Dec 27 22:27 io.pressure
-rw-r--r--  1 root root 0 Dec 27 22:27 memory.pressure
drwxr-xr-x 50 root root 0 Dec 27 22:48 system.slice
drwxr-xr-x  3 root root 0 Dec 27 22:27 user.slice
$ cat /sys/fs/cgroup/cgroup.controllers                                                                                                                                                                    
cpuset cpu io memory pids rdma
$ ls -l /sys/fs/cgroup/system.slice
total 0
drwxr-xr-x 2 root root 0 Dec 27 22:27  accounts-daemon.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  atd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  boot-efi.mount
-r--r--r-- 1 root root 0 Dec 27 22:27  cgroup.controllers
-r--r--r-- 1 root root 0 Dec 27 22:26  cgroup.events
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.freeze
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.max.depth
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.max.descendants
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.procs
-r--r--r-- 1 root root 0 Dec 27 22:27  cgroup.stat
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.subtree_control
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.threads
-rw-r--r-- 1 root root 0 Dec 27 22:27  cgroup.type
drwxr-xr-x 2 root root 0 Dec 27 22:27  containerd.service
-rw-r--r-- 1 root root 0 Dec 27 22:26  cpu.max
-rw-r--r-- 1 root root 0 Dec 27 22:27  cpu.pressure
-r--r--r-- 1 root root 0 Dec 27 22:27  cpu.stat
-rw-r--r-- 1 root root 0 Dec 27 22:27  cpu.uclamp.max
-rw-r--r-- 1 root root 0 Dec 27 22:27  cpu.uclamp.min
-rw-r--r-- 1 root root 0 Dec 27 22:26  cpu.weight
-rw-r--r-- 1 root root 0 Dec 27 22:27  cpu.weight.nice
-rw-r--r-- 1 root root 0 Dec 27 22:26  cpuset.cpus
-r--r--r-- 1 root root 0 Dec 27 22:27  cpuset.cpus.effective
-rw-r--r-- 1 root root 0 Dec 27 22:27  cpuset.cpus.partition
-rw-r--r-- 1 root root 0 Dec 27 22:26  cpuset.mems
-r--r--r-- 1 root root 0 Dec 27 22:27  cpuset.mems.effective
drwxr-xr-x 2 root root 0 Dec 27 22:27  cron.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  dbus.service
drwxr-xr-x 2 root root 0 Dec 27 22:27 'dev-disk-by\x2duuid-1ed8e2a2\x2d9157\x2d4e53\x2da24a\x2d82691a3d8bd6.swap'
drwxr-xr-x 2 root root 0 Dec 27 22:27 'dev-disk-by\x2duuid-6e67a025\x2d3711\x2d426f\x2db623\x2dd042f4400967.swap'
drwxr-xr-x 2 root root 0 Dec 27 22:27  dev-hugepages.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  dev-mqueue.mount
drwxr-xr-x 5 root root 0 Dec 27 22:38  docker-29230f1ebf3c4c659ae85816c3908470b28bf5607b499455b01f9d7b417e9b57.scope
drwxr-xr-x 2 root root 0 Dec 27 22:40  docker-7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a.scope
drwxr-xr-x 5 root root 0 Dec 27 22:38  docker-e4c32fcecf51cd6d5bf24c876d6cdca1eda979624eada8f3d1cc2451eb28a70a.scope
drwxr-xr-x 2 root root 0 Dec 27 22:27  docker.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  docker.socket
-rw-r--r-- 1 root root 0 Dec 27 22:27  io.max
-rw-r--r-- 1 root root 0 Dec 27 22:27  io.pressure
-r--r--r-- 1 root root 0 Dec 27 22:27  io.stat
-rw-r--r-- 1 root root 0 Dec 27 22:26  io.weight
drwxr-xr-x 2 root root 0 Dec 27 22:27  irqbalance.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  mdmonitor.service
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.current
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.events
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.events.local
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.high
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.low
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.max
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.min
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.oom.group
-rw-r--r-- 1 root root 0 Dec 27 22:27  memory.pressure
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.stat
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.swap.current
-r--r--r-- 1 root root 0 Dec 27 22:27  memory.swap.events
-rw-r--r-- 1 root root 0 Dec 27 22:26  memory.swap.max
drwxr-xr-x 2 root root 0 Dec 27 22:27  mnt-data.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  multipathd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  networkd-dispatcher.service
drwxr-xr-x 2 root root 0 Dec 27 22:48  packagekit.service
-r--r--r-- 1 root root 0 Dec 27 22:27  pids.current
-r--r--r-- 1 root root 0 Dec 27 22:27  pids.events
-rw-r--r-- 1 root root 0 Dec 27 22:26  pids.max
drwxr-xr-x 2 root root 0 Dec 27 22:27  polkit.service
-r--r--r-- 1 root root 0 Dec 27 22:47  rdma.current
-rw-r--r-- 1 root root 0 Dec 27 22:47  rdma.max
drwxr-xr-x 2 root root 0 Dec 27 22:27  rsyslog.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-core-11993.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-core20-1242.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-core20-1270.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-lxd-21835.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-snapd-14066.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snap-snapd-14295.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  snapd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  snapd.socket
drwxr-xr-x 2 root root 0 Dec 27 22:27  ssh.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  sys-fs-fuse-connections.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  sys-kernel-config.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  sys-kernel-debug.mount
drwxr-xr-x 2 root root 0 Dec 27 22:27  sys-kernel-tracing.mount
drwxr-xr-x 3 root root 0 Dec 27 22:27  system-getty.slice
drwxr-xr-x 2 root root 0 Dec 27 22:27  system-modprobe.slice
drwxr-xr-x 3 root root 0 Dec 27 22:27 'system-serial\x2dgetty.slice'
drwxr-xr-x 2 root root 0 Dec 27 22:27 'system-systemd\x2dfsck.slice'
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-journald.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-logind.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-networkd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-resolved.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-timesyncd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  systemd-udevd.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  udisks2.service
drwxr-xr-x 2 root root 0 Dec 27 22:27  unattended-upgrades.service
```

If we take the nginx container example I've spin up before, with a memory limit of 200m, we can clearly see this is effective here:

```
$ cat /sys/fs/cgroup/system.slice/docker-7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a.scope/memory.max
209715200
$ cat /sys/fs/cgroup/system.slice/docker-7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a.scope/memory.current
17825792
$ cat /sys/fs/cgroup/system.slice/docker-7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a.scope/memory.swap.max
209715200
$ cat /sys/fs/cgroup/system.slice/docker-7a0c2a2061ed2579a3d593dc835a106e47905b992a82382354245b05512ccd9a.scope/memory.swap.current
0
```

**Comment by fastlorenzo** [comment]
> 
> It seems ( for me ) only reported, when using multi-node setup. I've tried it with cri-o and containerd, both with same results ( ie. error reported ).
> 

@miroslav-beranic I did some tests based on your comment, it's, I believe, related to the usage of the `--memory` parameter.

I can have multiple nodes, but then it limits the total amount of memory to 16G, spread across all nodes.

**Comment by klaases** [comment]
Hi @cmanzur, did you find this issue to be related to the `--memory` parameter as  @fastlorenzo mentioned above?

**Comment by cmanzur** [comment]
Hi @klaases, yes. On Ubuntu the filename is: `/sys/fs/cgroup/memory/memory.memsw.limit_in_bytes` instead of `/sys/fs/cgroup/memory/memsw.limit_in_bytes`
That's why the HasMemoryCgroup check fails.

**Comment by warent** [comment]
I'm on Ubuntu 20.04 and there is no file `/sys/fs/cgroup/memory/memory.memsw.limit_in_bytes`, but there is `/sys/fs/cgroup/memory/memory.memory.limit_in_bytes`

there is no `memsw` anything.

Not sure if it's the same thing?

**Comment by xinmans** [comment]
i'm run on unbunt20.04, encount this message, but check the docker status, limit is 6G, what's wrong?
[admin@k8s2 ~]$ minikube start --memory=3069mb
😄  Centos 8.5.2111 (kvm/amd64) 上的 minikube v1.24.0
✨  根据现有的配置文件使用 docker 驱动程序
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
❗  You cannot change the memory size for an existing minikube cluster. Please first delete the cluster.

⛔  Requested memory allocation (1816MB) is less than the recommended minimum 1900MB. Deployments may fail.

👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  正在 Docker 20.10.8 中准备 Kubernetes v1.22.3…
🔎  Verifying Kubernetes components...
    ▪ Using image kubernetesui/dashboard:v2.3.1
    ▪ Using image kubernetesui/metrics-scraper:v1.0.7
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    ▪ Using image alpine:3.6
    ▪ Using image docker.elastic.co/kibana/kibana:5.6.2
    ▪ Using image k8s.gcr.io/elasticsearch:v5.6.2
    ▪ Using image k8s.gcr.io/fluentd-elasticsearch:v2.0.2
    ▪ Using image k8s.gcr.io/metrics-server/metrics-server:v0.4.2
🌟  Enabled addons: default-storageclass, storage-provisioner, metrics-server, efk, dashboard
❗  The image 'kibana/kibana:5.6.2-custom' was not found; unable to add it to cache.
❗  The image 'kibana/kibana:5.6.2' was not found; unable to add it to cache.
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
[admin@k8s2 ~]$ kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS             RESTARTS         AGE
default                balanced-5744b548b4-csws5                    1/1     Running            8 (10m ago)      66d
default                hello-minikube-6ddfcc9757-bhgds              1/1     Running            8 (10m ago)      66d
kube-system            coredns-78fcd69978-wc5p5                     1/1     Running            10 (10m ago)     66d
kube-system            elasticsearch-logging-rnrkm                  1/1     Running            0                31d
kube-system            elasticsearch-logging-rx599                  0/1     Error              4                66d
kube-system            etcd-minikube                                1/1     Running            8 (10m ago)      66d
kube-system            fluentd-es-qk5l6                             0/1     CrashLoopBackOff   13 (41s ago)     66d
kube-system            kibana-logging-ln44k                         1/1     Running            8 (10m ago)      66d
kube-system            kube-apiserver-minikube                      1/1     Running            10 (10m ago)     66d
kube-system            kube-controller-manager-minikube             1/1     Running            10 (10m ago)     66d
kube-system            kube-proxy-l4grw                             1/1     Running            8 (10m ago)      66d
kube-system            kube-scheduler-minikube                      1/1     Running            9 (10m ago)      66d
kube-system            metrics-server-77c99ccb96-l6kqn              1/1     Running            17 (2m16s ago)   66d
kube-system            storage-provisioner                          1/1     Running            18 (19m ago)     66d
kubernetes-dashboard   dashboard-metrics-scraper-5594458c94-b9fwb   1/1     Running            9 (10m ago)      66d
kubernetes-dashboard   kubernetes-dashboard-654cf69797-9k4rf        1/1     Running            15 (2m19s ago)   66d
[admin@k8s2 ~]$ docker stats --no-stream -a
CONTAINER ID   NAME                CPU %     MEM USAGE / LIMIT     MEM %     NET I/O         BLOCK I/O         PIDS
f3b5b90df30b   reverent_chatelet   0.00%     0B / 0B               0.00%     0B / 0B         0B / 0B           0
106d960ed953   minikube            69.19%    2.038GiB / 5.617GiB   36.27%    349kB / 582kB   51.9MB / 88.1kB   510
d469fabb43df   beautiful_keller    0.00%     0B / 0B               0.00%     0B / 0B         0B / 0B           0
[admin@k8s2 ~]$

**Comment by sharifelgamal** [comment]
It would seem like we need to check both `/sys/fs/cgroup/memory/memory.memsw.limit_in_bytes` and `/sys/fs/cgroup/memory/memory.limit_in_bytes`, which feels doable.

**Comment by kadern0** [comment]
@sharifelgamal, why not following same approach as docker (engine) and make use of `libcontainer/cgroups` as in:
https://github.com/docker/engine/blob/8955d8da8951695a98eb7e15bead19d402c6eb27/pkg/sysinfo/sysinfo_linux.go#L89
and https://github.com/docker/engine/blob/8955d8da8951695a98eb7e15bead19d402c6eb27/pkg/sysinfo/sysinfo_linux.go#L15 ?

In Ubuntu and Arch, I couldn't find either of these files so just did a quick test and this approach seems to work (although the testing was minimal). Happy to work on that approach if you think is worth it.

**Comment by j3zz3r** [comment]
Any updates on this ? 

```
$ dpkg -l |grep -i minik
ii  minikube                                      1.25.2-0                                    amd64        Minikube
$ minikube version
minikube version: v1.25.2
$ grep PRET /etc/*release
/etc/os-release:PRETTY_NAME="Ubuntu 20.04.4 LTS"
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
$ uname -r
5.4.0-100-generic
```

**Comment by kadern0** [comment]
@j3zz3r, I've pushed a branch that seems to fix the issue (at least in Ubuntu) but I'd like to further test it before sending a PR. If you want to test it, you can find it at https://github.com/kadern0/minikube/tree/issue-12842 any feedback would be much appreciated

**Comment by vuldin** [comment]
> @j3zz3r, I've pushed a branch that seems to fix the issue (at least in Ubuntu) but I'd like to further test it before sending a PR. If you want to test it, you can find it at https://github.com/kadern0/minikube/tree/issue-12842 any feedback would be much appreciated

I'll test this out later today, but I looked over the documentation and didn't immediately see how to install from source. I've just installed minikube through the getting started steps or via arkade. The getting started steps mention pointing to a release on a github repo, but I see no releases on your repo.

Do you have steps to get your branch's minikube version installed?

**Comment by kadern0** [comment]
@vuldin, if you follow the instructions [here](https://minikube.sigs.k8s.io/docs/contrib/building/binaries/) you can build minikube yoursel. You will have to use my git repo and checkout to the `issue-12842` branch

**Comment by vuldin** [comment]
hey @kadern0 , it looks like I still have the same issue. Here is the output:
```sh
> ./out/minikube start --memory=8192 --cpus 2 --kubernetes-version=v1.22.1
😄  minikube v1.25.2 on Ubuntu 22.04
🆕  Kubernetes 1.23.5 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.23.5
✨  Using the docker driver based on existing profile
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
❗  Your cgroup does not allow setting memory.
    ▪ More information: https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.22.1 on Docker 20.10.13 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

I have ensure grub options are in place to enable setting the cgroup swap limit, and I can follow all steps shown in this blog post and they work:
https://fabianlee.org/2020/01/18/docker-placing-limits-on-container-memory-using-cgroups/

Let me know if there is anything else to test.

**Comment by hoppla20** [comment]
Hey, I just wanted to add, that @kadern0's fix works for me. I'm using PopOS 22.04:

`uname -a`:
```
Linux pop-os 5.16.19-76051619-generic #202204081339~1649696161~22.04~091f44b SMP PREEMPT Mon Apr 11 17 x86_64 x86_64 x86_64 GNU/Linux
```

`minikube version`:
```
minikube version: v1.25.2
commit: 2da5b65085d4a82eb255adeaae718926b6fe48b2
```

`ls -l /sys/fs/cgroup`:
```
-r--r--r--  1 root root 0 May  4 19:30 cgroup.controllers
-rw-r--r--  1 root root 0 May  5 10:14 cgroup.max.depth
-rw-r--r--  1 root root 0 May  5 10:14 cgroup.max.descendants
-rw-r--r--  1 root root 0 May  4 19:30 cgroup.procs
-r--r--r--  1 root root 0 May  5 10:14 cgroup.stat
-rw-r--r--  1 root root 0 May  4 19:30 cgroup.subtree_control
-rw-r--r--  1 root root 0 May  5 10:14 cgroup.threads
-rw-r--r--  1 root root 0 May  5 10:14 cpu.pressure
-r--r--r--  1 root root 0 May  4 19:30 cpuset.cpus.effective
-r--r--r--  1 root root 0 May  4 19:30 cpuset.mems.effective
-r--r--r--  1 root root 0 May  5 10:14 cpu.stat
drwxr-xr-x  2 root root 0 May  4 19:36 dev-hugepages.mount
drwxr-xr-x  2 root root 0 May  4 19:36 dev-mqueue.mount
drwxr-xr-x  2 root root 0 May  4 19:30 init.scope
-rw-r--r--  1 root root 0 May  5 10:14 io.cost.model
-rw-r--r--  1 root root 0 May  5 10:14 io.cost.qos
-rw-r--r--  1 root root 0 May  5 10:14 io.pressure
-rw-r--r--  1 root root 0 May  5 10:14 io.prio.class
-r--r--r--  1 root root 0 May  5 10:14 io.stat
-r--r--r--  1 root root 0 May  5 10:14 memory.numa_stat
-rw-r--r--  1 root root 0 May  5 10:14 memory.pressure
-r--r--r--  1 root root 0 May  5 10:14 memory.stat
-r--r--r--  1 root root 0 May  5 10:14 misc.capacity
drwxr-xr-x  2 root root 0 May  4 19:36 sys-fs-fuse-connections.mount
drwxr-xr-x  2 root root 0 May  4 19:36 sys-kernel-config.mount
drwxr-xr-x  2 root root 0 May  4 19:36 sys-kernel-debug.mount
drwxr-xr-x  2 root root 0 May  4 19:36 sys-kernel-tracing.mount
drwxr-xr-x 48 root root 0 May  5 10:08 system.slice
drwxr-xr-x  3 root root 0 May  4 19:36 user.slice
```

`cat /sys/fs/cgroup/cgroup.subtree_control `:
```
cpuset cpu io memory hugetlb pids rdma misc
```

with following kernel parameters (using systemd-boot):
```
systemd.unified_cgroup_hierarchy=1 swapaccount=1
```

`minikube start --cpus 6 --memory 24g --kubernetes-version=v1.20.11`:
```
😄  [minikube-local] minikube v1.25.2 on Debian bookworm/sid
✨  Automatically selected the docker driver
📌  Using Docker driver with the root privilege
👍  Starting control plane node minikube-local in cluster minikube-local
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.20.11 preload ...
    > preloaded-images-k8s-v18-v1...: 366.61 MiB / 366.61 MiB  100.00% 827.62 K
🔥  Creating docker container (CPUs=6, Memory=24576MB) ...
🐳  Preparing Kubernetes v1.20.11 on Docker 20.10.13 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
```

**Comment by kadern0** [comment]
Happy it is working for you, @hoppla20. @vuldin, I've tested it in Ubuntu and it worked for me, did you run `git checkout issue-12842` before running the make command?

**Comment by BohoCode** [comment]
What version was this fixed in?

**Comment by hoppla20** [comment]
[v1.26.0-beta.0](https://github.com/kubernetes/minikube/releases/tag/v1.26.0-beta.0)
You can see it in the release notes.
