### ISSUE TITLE
hyperkit start: Could not find an IP address for 6a:c7:25:8a:7f:2b

### ISSUE THREAD

**Issue by zhaytee** [kubernetes/minikube#1926]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

Please provide the following details:

**Environment**:

**Minikube version**: 0.22.0
- **OS**: macOS 10.12.6
- **VM Driver**: hyperkit
- **ISO version**: minikube-v0.23.3.iso
- **Install tools**: 
- **Others**:

**What happened**:
Cluster did not start:
```
$ minikube start --vm-driver hyperkit -v 10
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:58797
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) Calling .Start
(minikube) Generated UUID 23bf5b8b-93fe-11e7-b603-784f43517719
(minikube) Generated MAC 6a:c7:25:8a:7f:2b
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
E0907 11:56:39.075265   54829 start.go:143] Error starting host: Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for 6a:c7:25:8a:7f:2b
Temporary Error: Could not find an IP address for 6a:c7:25:8a:7f:2b
[... snip a ton of these errors...]
```

**What you expected to happen**:
The cluster starts normally.

**How to reproduce it** (as minimally and precisely as possible):
See above command

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I built `docker-machine-driver-hyperkit` myself, but got the minikube binary from the latest official release here on Github. If there's a more official place to get `docker-machine-driver-hyperkit`, I'll try using that one.

**Comment by r2d4** [comment]
Can you see if there are any entries in the `"/var/db/dhcpd_leases` file?

**Comment by zhaytee** [comment]
@r2d4 Yep, looks like there are two entries. I've since gone back to running minikube using virtualbox, which may be relevant to its contents:
```
$ cat /var/db/dhcpd_leases
{
	name=minikube
	ip_address=192.168.64.3
	hw_address=1,ce:8d:37:74:2a:93
	identifier=1,ce:8d:37:74:2a:93
	lease=0x59b2e6b9
}
{
	name=minikube
	ip_address=192.168.64.2
	hw_address=1,96:fe:4d:30:dd:21
	identifier=1,96:fe:4d:30:dd:21
	lease=0x599d2141
}
```

**Comment by zhaytee** [comment]
Hey folks. I rebuilt `docker-machine-driver-hyperkit` from the git repo at tag v0.22.0, deleted `~/.minikube`, deleted `/var/db/dhcpd_leases`, and tried to create a fresh cluster using minikube 0.22.0: `minikube start --vm-driver hyperkit -v 10`

First attempt, I get this curious error (curious because my laptop has over 50GB free; I suspect the error is referring to something else):
```
$ minikube start --vm-driver hyperkit -v 10
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Found binary path at ~/.local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:50171
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
(minikube) Calling .DriverName
Creating CA: ~/.minikube/certs/ca.pem
Creating client certificate: ~/.minikube/certs/cert.pem
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading ~/.minikube/cache/boot2docker.iso from file://~/.minikube/cache/iso/minikube-v0.23.3.iso...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
E0913 00:06:02.067017   10983 start.go:143] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: truncate ~/.minikube/machines/minikube/minikube.rawdisk: no space left on device.
```

So I try the same command again, and it gets past that point. But now I get a different error, a permissions issue with getting ssh going (it can't read id_rsa because it's owned by root?):
```
$ minikube start --vm-driver hyperkit -v 10
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Found binary path at ~/.local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:50177
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) Error reading pid file: open ~/.minikube/machines/minikube/hyperkit.json: no such file or directory
(minikube) Calling .Start
(minikube) Generated UUID 07a53fc3-9852-11e7-8a4e-acde48001122
(minikube) Generated MAC 6e:fd:b9:e9:1a:eb
(minikube) Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) Calling .GetConfigRaw
(minikube) Calling .DriverName
Waiting for SSH to be available...
Getting to WaitForSSH function...
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: native
<nil>
Error getting ssh command 'exit 0' : Error getting config for native Go SSH: open ~/.minikube/machines/minikube/id_rsa: permission denied
```

Here are the contents of `~/.minikube/machines/minikube`:
```
$ ls -l ~/.minikube/machines/minikube
total 434776
-rw-------  1 root        staff  111521792 Sep 13 00:05 boot2docker.iso
-rw-r--r--  1 root        staff    7187728 Sep 13 00:05 bzimage
-rw-------  1 zhaytee  staff       2545 Sep 13 00:06 config.json
-rw-r--r--  1 root        staff      65536 Sep 13 00:06 console-ring
-rw-r--r--  1 root        staff       2254 Sep 13 00:06 hyperkit.json
-rw-r--r--  1 root        staff          5 Sep 13 00:06 hyperkit.pid
-rw-------  1 root        staff       1679 Sep 13 00:05 id_rsa
-rw-------  1 root        staff        381 Sep 13 00:05 id_rsa.pub
-rw-r--r--  1 root        staff  103790296 Sep 13 00:06 initrd
-rw-r--r--  1 root        staff        206 Sep 13 00:06 isolinux.cfg
-rw-r--r--  1 root        staff       4608 Sep 13 00:06 minikube.rawdisk
lrwxr-xr-x  1 root        staff         12 Sep 13 00:06 tty@ -> /dev/ttys031
```

I had installed `docker-machine-driver-hyperkit` using the Makefile entry `install-hyperkit-driver`, which sets the owner to `root:wheel` and sets the setuid bit via `chmod u+s`.

Is there an obvious path to victory here? Wondering what I'm missing.

Thank you!

**Comment by antoineco** [comment]
I have the same error message as the OP as soon as I try to restart a stopped minikube VM **after a macOS reboot** (on only in that case):

`Temporary Error: Could not find an IP address for <mac_addr>`.

It should be mentioned that *<mac_addr>* is different after every invocation of `minikube start`.

`minikube v0.23.0`
`docker-machine-driver-hyperkit @10f2bb57`

**Comment by kenden** [comment]
I can only get it to work using `sudo`. 
Else I get:
```
virtio_net: Could not create vmnet interface, permission denied or no entitlement?
start.go:150] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: vmnet: error from vmnet.framework: -1
```

**Repro steps:**

```
$ make out/docker-machine-driver-hyperkit  # build docker-machine-driver-hyperkit
$ make  # build minikube
export PATH=$PATH:/Users/myuser/dev/go/src/k8s.io/minikube/out/  # add hyperkit driver to path

$ ./out/minikube start --vm-driver hyperkit -v 7
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Found binary path at /Users/myuser/devgo/src/k8s.io/minikube/out/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:57472
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
(minikube) Calling .DriverName
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) Downloading /Users/myuser/.minikube/cache/boot2docker.iso from file:///Users/myuser/.minikube/cache/iso/minikube-v0.23.5.iso...
(minikube) DBG | 2017/11/21 11:16:50 [INFO] Creating ssh key...
(minikube) DBG | 2017/11/21 11:16:50 [INFO] Creating raw disk image...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
(minikube) Generated UUID 171ba2a0-cea5-11e7-9b4d-3c15c2ce618a
(minikube) DBG | virtio_net: Could not create vmnet interface, permission denied or no entitlement?
E1121 11:16:53.072514   39579 start.go:150] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: vmnet: error from vmnet.framework: -1
.

# ----> virtio_net: Could not create vmnet interface, permission denied or no entitlement?
# ----> let's try with sudo

$ ./out/minikube delete
$ sudo ./out/minikube start --vm-driver hyperkit
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

$ kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     <none>    12s       v1.8.0
```

**Version:**
macOS 10.13.1 (High Sierra)

$ uname -a
Darwin apollo 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

**Comment by antoineco** [comment]
Did you forget to set the `setuid` flag on the `docker-machine-driver-hyperkit` cher Monsieur Nerden? (sudo chmod u+s out/docker-machine-driver-hyperkit)

**Comment by kenden** [comment]
@antoineco Indeed, merci gamin. When replacing my steps:
```
$ make out/docker-machine-driver-hyperkit  # build docker-machine-driver-hyperkit
$ export PATH=$PATH:/Users/myuser/dev/go/src/k8s.io/minikube/out/
```
by:
```
$ make install-hyperkit-driver
```
then it works fine without sudo.

**Comment by dlorenc** [comment]
Thanks for the update! We should add an error that helps track down when you forget to set setuid.

**Comment by dlorenc** [comment]
This should be fixed with #2215

**Comment by antoineco** [comment]
@dlorenc the original issue was not about permissions, rather about this error:

`Temporary Error: Could not find an IP address for <mac_addr>`

Can we please reopen?

**Comment by lightsofapollo** [comment]
Experiencing this as well... Only occurred after starting an initially working cluster then restarting my computer.

```
minikube version: v0.24.1
```

Some logs from start:

```
I1204 11:03:02.848364    8475 cache_images.go:290] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.0 at /Users/sahajalal/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0
I1204 11:03:02.848379    8475 cache_images.go:290] Attempting to cache image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.5 at /Users/sahajalal/.minikube/cache/images/gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64_1.14.5
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
I1204 11:03:02.848408    8475 cache_images.go:290] Attempting to cache image: gcr.io/google_containers/pause-amd64:3.0 at /Users/sahajalal/.minikube/cache/images/gcr.io/google_containers/pause-amd64_3.0
I1204 11:03:02.848405    8475 cache_images.go:290] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.2 at /Users/sahajalal/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.4-beta.2
I1204 11:03:02.848416    8475 cache_images.go:290] Attempting to cache image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.5 at /Users/sahajalal/.minikube/cache/images/gcr.io/google_containers/k8s-dns-kube-dns-amd64_1.14.5
I1204 11:03:02.848430    8475 cache_images.go:290] Attempting to cache image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.5 at /Users/sahajalal/.minikube/cache/images/gcr.io/google_containers/k8s-dns-sidecar-amd64_1.14.5
I1204 11:03:02.848418    8475 cache_images.go:290] Attempting to cache image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3 at /Users/sahajalal/.minikube/cache/images/gcr.io/google_containers/kubernetes-dashboard-amd64_v1.6.3
I1204 11:03:02.848505    8475 cluster.go:74] Skipping create...Using existing machine configuration
I1204 11:03:02.849033    8475 cache_images.go:78] Successfully cached all images.
I1204 11:03:02.910072    8475 cluster.go:83] Machine state:  Stopped
```

**Comment by lightsofapollo** [comment]
After running `minikube delete` then `minikube start --vm-driver hyperkit` I am back into a working state.

**Comment by joshuarubin** [comment]
FWIW, I tried making a new machine (which starts up fine), stopping it, copying the old machine's minikube.rawdisk, id_rsa and id_rsa.pub files to the new one. After doing this, the new machine reports the same `Error starting host:  Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for <mac_address>` when started.

Also, of note, I don't see any `docker-machine` being started, just `docker-machine-driver-hyperkit` with no arguments.

**Comment by ntfrnzn** [comment]
I've just run into this issue, also (to quote above)
> Only occurred after starting an initially working cluster then restarting my computer.

I observe (a) stopping and restarting a hyperkit-based minikube machine regenerates the mac address (b) after restarting the osx host, the hyperkit-based minikube machine will not update /var/db/dhcpd_leases at all.

It *seems* that a hyperkit-base minikube will not survive a host reboot, and that if you reboot, you must `minikube delete` and rebuild.  At least with v0.24.1

**Comment by antoineco** [comment]
I observed minikube survives OS restarts it is shut down with `minikube stop`. Have you tried that?

**Comment by dfang** [comment]
same issue, 

`minikube start` alwasy failed with error message:

```
E1225 11:23:41.469132   37265 start.go:156] Error starting host:  Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for 26:45:11:1a:c3:4
```

 `minikube start` only works after `minikube delete` ....

any updates ?

**Comment by zoidbergwill** [comment]
@dfang Have you tried fiddling with `/var/db/dhcpd_leases`?

**Comment by dfang** [comment]
@zoidbergwill  what do you mean by fiddling ...

here is the contents of the file:

```
> cat /var/db/dhcpd_leases
{
	name=minikube
	ip_address=192.168.64.12
	hw_address=1,8a:b2:f4:33:24:2a
	identifier=1,8a:b2:f4:33:24:2a
	lease=0x5a421617
}
{
	name=minikube
	ip_address=192.168.64.11
	hw_address=1,1a:a3:8f:9e:d7:ff
	identifier=1,1a:a3:8f:9e:d7:ff
	lease=0x5a42112b
}
{
	name=minikube
	ip_address=192.168.64.10
	hw_address=1,ca:ad:6f:8b:2f:e8
	identifier=1,ca:ad:6f:8b:2f:e8
	lease=0x5a420e4c
}
{
	name=minikube
	ip_address=192.168.64.9
	hw_address=1,aa:6d:8d:dd:3f:8e
	identifier=1,aa:6d:8d:dd:3f:8e
	lease=0x5a41d332
}
{
	name=minikube
	ip_address=192.168.64.8
	hw_address=1,ae:66:c5:ca:f9:64
	identifier=1,ae:66:c5:ca:f9:64
	lease=0x5a41c6d7
}
{
	name=minikube
	ip_address=192.168.64.7
	hw_address=1,16:15:9f:46:91:62
	identifier=1,16:15:9f:46:91:62
	lease=0x5a41c304
}
{
	name=minikube
	ip_address=192.168.64.6
	hw_address=1,62:f:5a:bf:b1:c9
	identifier=1,62:f:5a:bf:b1:c9
	lease=0x5a41c2cc
}
{
	name=minikube
	ip_address=192.168.64.5
	hw_address=1,32:12:5a:b7:4:20
	identifier=1,32:12:5a:b7:4:20
	lease=0x5a40b838
}
{
	name=minikube
	ip_address=192.168.64.4
	hw_address=1,a2:42:fb:6f:aa:eb
	identifier=1,a2:42:fb:6f:aa:eb
	lease=0x5a409c72
}
{
	name=minikube
	ip_address=192.168.64.3
	hw_address=1,1a:a8:38:7f:ca:90
	identifier=1,1a:a8:38:7f:ca:90
	lease=0x5a3f7925
}
{
	name=minikube
	ip_address=192.168.64.2
	hw_address=1,5a:23:fd:75:a1:b1
	identifier=1,5a:23:fd:75:a1:b1
	lease=0x5a3f5e40
}
```

**Comment by danielcoman** [comment]
I am experiencing the same issue after an unexpected shutdown. 
` Error starting host:  Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for 36:20:2:4d:48:32`
Cleared /var/db/dhcpd_leases an reinstalled Hyperkit as stated here: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md

**Comment by alanbrent** [comment]
The problem is that the `hyperkit.pid` file (e.g. `~/.minikube/machines/minikube/hyperkit.pid`) is taken as gospel, and the PID recorded in the file is not validated as a running `hyperkit` process. This is why it shows up when you e.g. reboot without first stopping `minikube`. When I get a little bit of time, I'm planning to take a deeper dive into the source. My first superficial search seems to indicate that the bug is actually in upstream Moby, but I don't have much confidence in that guess.

**Comment by jwandrews** [comment]
@dlorenc do you think this issue is related to #2416 ? if so, #2417 should resolve this issue.

**Comment by huguesalary** [comment]
@jwandrews seems to me that if #2417 fixes this issue, it only would as a side effect of re-assigning the same ip address. If, for example, `/var/db/dhcpd_leases` gets deleted, this bug (#1926) will happen again.

**Comment by jwandrews** [comment]
@huguesalary ahhh good to know. thanks

**Comment by alanbrent** [comment]
BTW, it appears that the specific failure case I mentioned in https://github.com/kubernetes/minikube/issues/1926#issuecomment-356378525 is still a problem in the latest release.

**Comment by sabinthomas** [comment]
I did try to just delete the `hyperkit.pid` but does not resolve the issue. I'd love to know if I need to be doing something different for @alanbrent 's [suggestion](https://github.com/kubernetes/minikube/issues/1926#issuecomment-356378525)

**Comment by danielcoman** [comment]
I've managed to make it work temporarily by deleting `hyperkit.pid` **and** emptying `/var/db/dhcpd_leases`. But this issue comes back quite often.

**Comment by LewisLebentz** [comment]
Also tried deleting `hyperkit.pid` and clearing `/var/db/dhcpd_leases` but can't even get it working temporarily.

**Comment by ditansu** [comment]
Hello, I clean  /var/db/dhcpd_leases,  somebody know how to fill it correct?

**Comment by antoineco** [comment]
@ditansu you have to delete your minikube VM as described in https://github.com/kubernetes/minikube/issues/1926#issuecomment-353419654.

**Comment by ditansu** [comment]
@antoineco  Thank you for your answer! Sure I've tried (many times) do it with have no a result. But when I disabled the ExpressVPN it did worked
May be my steps will be useful to somebody:
```bash
disable  and quit ExpressVPN
di@💻:kuber$ minikube delete
di@💻:kuber$ rm  -rf ~/.minikube
di@💻:kuber$ sudo rm /var/db/dhcpd_leases
restart docker by menu 
di@💻:kuber$ minikube start --vm-driver hyperkit  -v 10
....
di@💻:kuber$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.64.2
di@💻:kuber$ cat /var/db/dhcpd_leases
{
	name=minikube
	ip_address=192.168.64.2
	hw_address=1,2:f4:d4:c4:a0:99
	identifier=1,2:f4:d4:c4:a0:99
	lease=0x5af1527a
}
```

**Comment by antoineco** [comment]
> minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.64.2

The title of this issue is `New cluster w/ HyperKit driver fails to start`. Your cluster is obviously starting, so I'm not sure what the problem is exactly, but would you mind opening another issue for that?

**Comment by ditansu** [comment]
Dear @antoineco, I've had problem with HyperKit driver but  it IMO was solve by disabling VPN driver. Now I no have problem. Thank you.

**Comment by sabinthomas** [comment]
@antoineco 
Is there a less intrusive option than having to delete the VM as per your [comment](https://github.com/kubernetes/minikube/issues/1926#issuecomment-386987762). My issue is sometimes having the minikube VM failing to start after putting the Mac to sleep. Deleting the VM would make it impossible to continue working existing clusters on minikube. 

Would love to hear if there is anything else I can try?

**Comment by xorange** [comment]
I'm also experiencing the same problem and came from #2430 

OS: MacOS 10.13.6 High Sierra

**Comment by tstromberg** [comment]
I believe this is fixed with the latest hyperkit driver, released with v0.34.0. If you are running into this, please try running:

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
&& sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/
```

Thanks!

**Comment by condemil** [comment]
I still have the same issue

```bash
$ ls -la $(which docker-machine-driver-hyperkit)
-rwsr-xr-x 1 root wheel 27779836 Mar 12 17:51 /usr/local/bin/docker-machine-driver-hyperkit
```

**Comment by lvnilesh** [comment]
```
minikube start -v 10

o   minikube v0.35.0 on darwin (amd64)
>   Creating hyperkit VM (CPUs=6, Memory=32MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:51117
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Creating CA: /Users/cloudgenius/.minikube/certs/ca.pem
Creating client certificate: /Users/cloudgenius/.minikube/certs/cert.pem
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
(minikube) Calling .GetConfigRaw
Creating machine...
(minikube) Calling .Create
(minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
(minikube) Downloading /Users/cloudgenius/.minikube/cache/boot2docker.iso from file:///Users/cloudgenius/.minikube/cache/iso/minikube-v0.35.0.iso...
(minikube) DBG | Writing magic tar header
(minikube) DBG | Writing SSH key tar header
(minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
(minikube) DBG | clean start, hyperkit pid file doesn't exist: /Users/cloudgenius/.minikube/machines/minikube/hyperkit.pid
(minikube) DBG | Using UUID 8d693188-49de-11e9-899c-a860b6394002
(minikube) DBG | Generated MAC 42:a1:80:82:83:66
(minikube) DBG | Starting with cmdline: loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
(minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
(minikube) DBG | hyperkit pid from json: 36779
(minikube) DBG | Searching for 42:a1:80:82:83:66 in /var/db/dhcpd_leases ...
(minikube) DBG | 2019/03/18 17:33:02 fcntl(F_PUNCHHOLE) failed: host filesystem does not support sparse files: Operation not permitted
(minikube) DBG | 2019/03/18 17:33:02 kexec: failed to load kernel /Users/cloudgenius/.minikube/machines/minikube/bzimage
(minikube) DBG | 2019/03/18 17:33:02 linkname /Users/cloudgenius/.minikube/machines/minikube/tty
(minikube) DBG | 2019/03/18 17:33:02 COM1 connected to /dev/ttys003
(minikube) DBG | 2019/03/18 17:33:02 COM1 linked to /Users/cloudgenius/.minikube/machines/minikube/tty
(minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
(minikube) DBG | hyperkit pid from json: 36779
(minikube) DBG | hyperkit pid 36779 missing from process table
!   Unable to start VM: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
hyperkit crashed! command line:
  hyperkit loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

**Comment by rajahafify** [comment]
I don't get why this issue is closed while a few people still facing this issue like myself.
```
 ❯ ls -la $(which docker-machine-driver-hyperkit)                                                                                                   
-rwsr-xr-x  1 root  wheel    32M Jul 18 12:24 /usr/local/bin/docker-machine-driver-hyperkit
```

**Comment by joshuarli** [comment]
Anecdotal, but these errors seem to occur when resources (memory, disk) are underallocated/unavailable. The defaults (CPUs=2, Memory=2048MB, Disk=20000MB) work though.

**Comment by EfraimLA** [comment]
hi i'm getting the same issue too, i'd tried installing different hyperkit driver versions though, i'll not work  ):


`-- Starting profile 'minishift'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'hyperkit' is supported on this platform ... OK
-- Checking the ISO URL ... OK
-- Checking if provided oc flags are supported ... OK
-- Starting the OpenShift cluster using 'hyperkit' hypervisor ...
-- Starting Minishift VM .......................... FAIL E0820 15:33:05.942306    3028 start.go:494] Error starting the VM: Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4. Retrying.
Error starting the VM: Error starting stopped host: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4
Temporary Error: Could not find an IP address for c6:b6:64:d5:19:f4`

**Comment by paljsingh** [comment]
I got this error when working over VPN.
`minikube start` works after I disconnect from the VPN.

```
$ minikube start --vm-driver=hyperkit --cpus=4 --memory=8192
😄  minikube v1.3.1 on Darwin 10.13.6
🔥  Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
E0821 12:21:12.559082    5427 start.go:723] StartHost: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 86:ac:fd:ec:6:cf

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 86:ac:fd:ec:6:cf

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

```
$ cat /var/db/dhcpd_leases
{
	name=minikube
	ip_address=192.168.64.5
	hw_address=1,da:ce:5c:8f:89:1
	identifier=1,da:ce:5c:8f:89:1
	lease=0x5d5e39e7
}
{
	name=minikube
	ip_address=192.168.64.4
	hw_address=1,66:f3:ea:fa:78:5f
	identifier=1,66:f3:ea:fa:78:5f
	lease=0x5d5e3709
}
{
	name=minikube
	ip_address=192.168.64.3
	hw_address=1,1a:9b:39:de:59:b8
	identifier=1,1a:9b:39:de:59:b8
	lease=0x5d5e32c7
}
{
	name=minikube
	ip_address=192.168.64.2
	hw_address=1,e6:79:d3:af:bb:24
	identifier=1,e6:79:d3:af:bb:24
	lease=0x5d5e3291
}
```

**Comment by jenildoshi** [comment]
I read all the above comments. Tried below steps,

`ls -la $(which docker-machine-driver-hyperkit)
-rwsr-xr-x  1 root  wheel  11314532 Nov 21 10:41 /usr/local/bin/docker-machine-driver-hyperkit`

Also ran, 
`minikube delete && minikube start --vm-driver=hyperkit`
`minikube start --disk-size 35g --memory 8192 --vm-driver hyperkit`

I still get the same error and I am not connected to VPN too.
`🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory`

**Comment by ossie-git** [comment]
Based on @paljsingh's suggestion, I turned off my VPN connection and it worked.  Haven't debugged the root cause but I now have:

```
macbook:~ me$ minikube start --vm-driver=hyperkit
😄  minikube v1.5.2 on Darwin 10.13.6
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
💾  Downloading kubelet v1.16.2
💾  Downloading kubeadm v1.16.2
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
```
