### ISSUE TITLE
add `minikube image login` command

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#21685]
add `minikube image login` command
should login to a docker hub or other regsitries
using a user pass or token

minikube image login -u user1 -p TOKEN_OR_Password -r hub.docker.com

**Comment by nirs** [comment]
Before we try to implement this we ned to validate the assumptions that `docker login` in the guest make image pull in k8s authenticated.

I think the way to validate it is:
1. create an account in dockerhub if needed
1. create a read only token for pulling images
1. upload an image to a private repository that can be pull only with your password or the token
1. deploy a pod using this image - it should fail to pull the image
1. run docker login inside the cluster with your read only token
1. deploy a pod using this image - it should work now

If this does not work there is no point in adding image login command.

**Comment by henry3260** [comment]
> Before we try to implement this we ned to validate the assumptions that `docker login` in the guest make image pull in k8s authenticated.
> 
> I think the way to validate it is:
> 
> 1. create an account in dockerhub if needed
> 2. create a read only token for pulling images
> 3. upload an image to a private repository that can be pull only with your password or the token
> 4. deploy a pod using this image - it should fail to pull the image

Here is the result when I tried to deploy a pod using the private image — it failed to pull as expected:

<img width="1275" height="720" alt="Image" src="https://github.com/user-attachments/assets/1defd499-42e2-4889-a88f-8edf0c2919b6" />

**Comment by henry3260** [comment]
> 5. run docker login inside the cluster with your read only token
> 6. deploy a pod using this image - it should work now

login-pod.yaml

<img width="496" height="356" alt="Image" src="https://github.com/user-attachments/assets/9edcf59d-6d36-4469-966b-34a13275b87f" />

I execute the docker login in this pod and it is success.

but it failed
<img width="977" height="722" alt="Image" src="https://github.com/user-attachments/assets/af9b5b0a-d1fc-463a-9cdc-f81ce925c79c" />

As you can see, even after running docker login inside the cluster (step 5), the pod still failed to pull the private image (step 6). This confirms that docker login inside a pod does not affect Kubernetes image pulls. The correct approach should be using imagePullSecrets

**Comment by nirs** [comment]
> > 5. run docker login inside the cluster with your read only token
> > 6. deploy a pod using this image - it should work now
> 
> login-pod.yaml
> I execute the docker login in this pod and it is success.

In the login command we are going to run docker login via ssh. Running it in a pod may not have the same effect, depending on the implementation. For example in podman when you run podman login pdman create a file in:

```
~/.config/containers/auth.json
```

If the docker command does something similar login in the pod is not the same as login on the host.

Try this again via ssh.

> but it failed 
> As you can see, even after running docker login inside the cluster (step 5), the pod still failed to pull the private image (step 6). This confirms that docker login inside a pod does not affect Kubernetes image pulls. The correct approach should be using imagePullSecrets

I'm not sure it your test was correct, but it is likely this does not work.

It can work only if docker stores the login information at the daemon level and use it for all pulls.

**Comment by henry3260** [comment]
> In the login command we are going to run docker login via ssh. Running it in a pod may not have the same effect, depending on the implementation. For example in podman when you run podman login pdman create a file in:
> 
> ```
> ~/.config/containers/auth.json
> ```
> 
> If the docker command does something similar login in the pod is not the same as login on the host.
> 
> Try this again via ssh

First I logged into Docker on the node via `minikube ssh` using a read-only token.  
Then I applied `success-pod.yml`, but the pod still failed with `ImagePullBackOff`.  
So you are right — it seems that the Kubernetes runtime does not read `~/.docker/config.json` from the host.

**Comment by nirs** [comment]
> First I logged into Docker on the node via `minikube ssh` using a read-only token. Then I applied `success-pod.yml`, but the pod still failed with `ImagePullBackOff`. So you are right — it seems that the Kubernetes runtime does not read `~/.docker/config.json` from the host.

So I think the next step is to understand how image loading works when running stating a pod. Can we configure it to use a static configuration file for the entire cluster? 

This does not make sense for a real cluster where you have many users and each user has its own images. But in minikube we have single user and it will help to have single login for the entire cluster.

**Comment by nirs** [comment]
If we don't find how to inject login info to the entire cluster we can automate creation of image pull secret per namespace:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account

**Comment by nirs** [comment]
Another option to check is configuring the kubelt credentials provider:
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/

We can add a plugin reading the credentations from the node docker config.json. Maybe such plugin already exists.

The protocol seems to be documented here:
https://kubernetes.io/docs/reference/config-api/kubelet-credentialprovider.v1/

The docs says

> CredentialProviderRequest includes the image that the kubelet requires authentication for. Kubelet will pass this request object to the plugin via stdin

"Pass this request object via stdin" means the object must be serialized in some way. The document does not mention the serialization but AI mode suggests this is JSON encoded like all communication using k8s APIs.

So the plugin can do:

1. Decode json from stdin into CredentialProviderRequest
2. Read a config file with the auth details
3. Check if the image matches the config (e.g. have docker hub auth for images in docker hub)
4. Create CredentialProviderResponse with the auth details
5. Encode the CredentialProviderResponse as JSON to stdout

There is an example here:
staging/src/k8s.io/kubelet/cmd/credential-provider-echo-token/main.go

**Comment by medyagh** [comment]
Lets Try This and let see if this works with docker access token.
```
$ minikube addons configure registry-creds
Do you want to enable AWS Elastic Container Registry? [y/n]: n

Do you want to enable Google Container Registry? [y/n]: y
-- Enter path to credentials (e.g. /home/user/.config/gcloud/application_default_credentials.json):/home/user/.config/gcloud/application_default_credentials.json

Do you want to enable Docker Registry? [y/n]: n
```

**Comment by henry3260** [comment]
> Lets Try This and let see if this works with docker access token.

I am unable to use `minikube addons configure registry-creds` successfully. It fails with the error shown below.

Does this command require a specific setup?

<img width="783" height="380" alt="Image" src="https://github.com/user-attachments/assets/dc5d8d83-0f6a-45a4-a04b-528dc3999dbe" />

**Comment by nirs** [comment]
@henry3260 please do not add images when you can copy and paste the text.

You can open an issue for this error. No minikube command should fail like this.

**Comment by henry3260** [comment]
### 1. Start minikube with Docker driver:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube start --driver=docker
😄  minikube v1.37.0 on Ubuntu 24.04 (kvm/amd64)
✨  Using the docker driver based on user configuration
📌  Using Docker driver with root privileges
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🚜  Pulling base image v0.0.48-1760939008-21773 ...
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
🐳  Preparing Kubernetes v1.34.1 on Docker 28.5.1 ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### 2. Configure registry-creds addon for private Docker registry:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube addons configure registry-creds

Do you want to enable AWS Elastic Container Registry? [y/n]: n

Do you want to enable Google Container Registry? [y/n]: n

Do you want to enable Docker Registry? [y/n]: y
-- Enter docker registry server url: docker.io
-- Enter docker registry username: henry0512
-- Enter docker registry password: 

Do you want to enable Azure Container Registry? [y/n]: n
✅  registry-creds was successfully configured
```

### 3. Enable the addon:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube addons enable registry-creds
❗  registry-creds is a 3rd party addon and is not maintained or verified by minikube maintainers, enable at your own risk.
❗  registry-creds does not currently have an associated maintainer.
    ▪ Using image docker.io/upmcenterprises/registry-creds:1.10
🌟  The 'registry-creds' addon is enabled
```


### 4. Run a test pod using the private image:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube kubectl -- run test-pull \
--image=docker.io/henry0512/test-private-image:latest \
--image-pull-policy=Always
pod/test-pull created
```

### 5. Check pod status:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube kubectl -- get pod test-pull -w
NAME        READY   STATUS    RESTARTS   AGE
test-pull   1/1     Running   0          78s
```

### 6. Verify that the image is cached in minikube:

```
henry@DESKTOP-KILRQMD:~/minikube$ ./out/minikube image ls --format table | grep test-private-image
│ docker.io/henry0512/test-private-image   │ latest  │ 07ccdb7838758 │ 160MB  │
```

### 7. Cluster status after testing registry-creds addon:

```
$ ./out/minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

$ ./out/minikube kubectl -- get nodes
NAME       STATUS   ROLES           AGE   VERSION
minikube   Ready    control-plane   11m   v1.34.1

$ ./out/minikube kubectl -- get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS      AGE
default       test-pull                          1/1     Running   0             4m37s
kube-system   coredns-66bc5c9577-dldtz           1/1     Running   0             11m
kube-system   etcd-minikube                      1/1     Running   0             11m
kube-system   kube-apiserver-minikube            1/1     Running   0             11m
kube-system   kube-controller-manager-minikube   1/1     Running   0             11m
kube-system   kube-proxy-tdkkm                   1/1     Running   0             11m
kube-system   kube-scheduler-minikube            1/1     Running   0             11m
kube-system   registry-creds-764b6fb674-vr5vc    1/1     Running   0             5m58s
kube-system   storage-provisioner                1/1     Running   1 (11m ago)   11m
```

All steps completed successfully, registry-creds addon is functioning, and private Docker images can be pulled and cached in the cluster.
