### ISSUE TITLE
cache add: Error caching and loading images: Process exited with status 1

### ISSUE THREAD

**Issue by abhinav-chittora** [kubernetes/minikube#2478]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG**

Please provide the following details:

**Environment**:
```
- Minikube version: v0.25.0
- OS : Windows 10
- VM Driver: virtualbox 
- ISO version :  v0.25.1
- Install tools:
- Others:
```
**What happened**: When I run `minikube cache add ubuntu:16.04` it gives following error:- 
```Error caching and loading images: loading cached images: loading image C:\Users\Abhinav Chittora\.minikube\cache\images\ubuntu: loading docker image: \tmp\ubuntu: Process exited with status 1```

**What you expected to happen**: It should cache the given image. 

**How to reproduce it** (as minimally and precisely as possible): Install minikube, run `minikube start` and run the command `minikube cache add ubuntu:16.04`

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by prat0318** [comment]
Facing the same issue ^

**Comment by lleszczu** [comment]
I'm experiencing same issue on macOS high sierra.

**Comment by JrCs** [comment]
Same issue with minikube 0.27

**Comment by seglo** [comment]
I get this error when loading an image from my cache that I built locally.  If it's a dockerhub image it seems to load fine.

```
# successfully cache image pulled from docker hub

seglo@slice  ~/source/strimzi   master  minikube cache add strimzi/cluster-operator:latest -v 7 --alsologtostderr                                                                                                                                                                              
I0625 16:50:09.723416   15731 cache_images.go:292] Attempting to cache image: strimzi/cluster-operator:latest at /home/seglo/.minikube/cache/images/strimzi/cluster-operator_latest
I0625 16:50:09.723641   15731 cache_images.go:79] Successfully cached all images.
I0625 16:50:09.771127   15731 cache_images.go:194] Loading image from cache at  /home/seglo/.minikube/cache/images/strimzi/cluster-operator_latest
I0625 16:50:09.771201   15731 ssh_runner.go:58] Run: sudo rm -f /tmp/cluster-operator_latest
I0625 16:50:09.820178   15731 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0625 16:50:12.558524   15731 ssh_runner.go:58] Run: docker load -i /tmp/cluster-operator_latest
I0625 16:50:12.811584   15731 ssh_runner.go:58] Run: sudo rm -rf /tmp/cluster-operator_latest
I0625 16:50:12.870644   15731 cache_images.go:220] Successfully loaded image /home/seglo/.minikube/cache/images/strimzi/cluster-operator_latest from cache
I0625 16:50:12.870686   15731 cache_images.go:99] Successfully loaded all cached images.

# unsuccessfully cache image built locally

 seglo@slice  ~/source/strimzi   master  minikube cache add seglo/cluster-operator:latest -v 7 --alsologtostderr                                                                                                                                                                                  
I0625 16:53:44.297430   16074 cache_images.go:292] Attempting to cache image: seglo/cluster-operator:latest at /home/seglo/.minikube/cache/images/seglo/cluster-operator_latest
I0625 16:53:44.297576   16074 cache_images.go:79] Successfully cached all images.
I0625 16:53:44.325572   16074 cache_images.go:194] Loading image from cache at  /home/seglo/.minikube/cache/images/seglo/cluster-operator_latest
I0625 16:53:44.325634   16074 ssh_runner.go:58] Run: sudo rm -f /tmp/cluster-operator_latest
I0625 16:53:44.376862   16074 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0625 16:53:44.433219   16074 ssh_runner.go:58] Run: docker load -i /tmp/cluster-operator_latest
Error caching and loading images: loading cached images: loading image /home/seglo/.minikube/cache/images/seglo/cluster-operator_latest: loading docker image: /tmp/cluster-operator_latest: Process exited with status 1

```

**Comment by brodster2** [comment]
Facing the same issue on macOS High Sierra.
- Minikube version: 0.28.0
- VM Driver: Virtualbox

```shell
$ minikube cache add hdp/kdc:v1 --alsologtostderr

I0710 10:52:13.036196   44862 notify.go:109] Checking for updates...
I0710 10:52:13.271576   44862 cache_images.go:293] Attempting to cache image: hdp/kdc:v1 at /Users/brodie/.minikube/cache/images/hdp/kdc_v1
I0710 10:52:13.273680   44862 cache_images.go:80] Successfully cached all images.
I0710 10:52:13.304614   44862 cache_images.go:195] Loading image from cache at  /Users/brodie/.minikube/cache/images/hdp/kdc_v1
I0710 10:52:13.304755   44862 ssh_runner.go:57] Run: sudo rm -f /tmp/kdc_v1
I0710 10:52:13.317181   44862 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0710 10:52:13.336345   44862 ssh_runner.go:57] Run: docker load -i /tmp/kdc_v1
Error caching and loading images: loading cached images: loading image /Users/brodie/.minikube/cache/images/hdp/kdc_v1: loading docker image: /tmp/kdc_v1: Process exited with status 1
```

**Comment by jberkus** [comment]
It works for me on:

* minikube 0.28
* Fedora 28
* KVM2

Been able to cache images, and then use them without downloading later.

**Comment by jberkus** [comment]
/remove lifecycle-rotten

This appears to still be an issue on many platforms, I just got another report of a user experiencing it.  Oddly, it seems to affect some container images but not others.

**Comment by jberkus** [comment]
/remove-lifecycle rotten

So here's another twist.  I just tested migrating an image from a private registry to docker hub, shortening its name, and it worked on a Mac OSX machine where "cache add" had been failing.  So maybe this is either (a) an issue with non-Hub registries or (b) an issue with the length of image names?

**Comment by seglo** [comment]
@jberkus Yes, when I observed this issue it was only caused by local images I had created, but that had not been uploaded to a registry yet.

**Comment by jberkus** [comment]
To be completely clear, but "private registry" I mean "something that is not Docker Hub or Quay.io".  Not local images.

**Comment by seglo** [comment]
Got it.  In my case I was trying to add images I pushed to the minikube local docker daemon, but that weren't in any other registry.

**Comment by tstromberg** [comment]
Based on the comments, this may be two different bugs:

- "cache add" may not be working in Windows
- "cache add" may not be working with repositories which require authentication

Either way, it's the docker command which is failing, so we need the output from it.  Can someone who is running into this execute the following, and attach the logs?

```shell
minikube cache add <your tag>  --v=5 --alsologtostderr  
```

It should then say which docker command failed. If you don't mind, run it and paste the output, such as: `docker load -i /tmp/kdc_v1`

**Comment by rveguilla** [comment]
> Based on the comments, this may be two different bugs:
> 
> * "cache add" may not be working in Windows
> * "cache add" may not be working with repositories which require authentication
>

@tstromberg I just tested again, this time on both macOS and Linux (Fedora) by doing the following (I'm not sure if  minikube need to be running for the `cache add` operation to work, so I started minikube just in case):
```
minikube delete
rm -rf ~/.minikube
rm -f ~/.docker/config.json
minikube start
```
Then when I try `cache add` I get the following error:
```
>  minikube cache add mysql:5 --v=5 --alsologtostderr 
W0921 15:12:15.211679   20266 root.go:148] Error reading config file at /home/rveguilla/.minikube/config/config.json: open /home/rveguilla/.minikube/config/config.json: no such file or directory
I0921 15:12:15.212162   20266 notify.go:121] Checking for updates...
I0921 15:12:15.296897   20266 cache_images.go:280] Attempting to cache image: mysql:5 at /home/rveguilla/.minikube/cache/images/mysql_5
2018/09/21 15:12:15 Unable to read "/home/rveguilla/.docker/config.json", falling back on anonymous: open /home/rveguilla/.docker/config.json: no such file or directory
Error caching and loading images: caching images: caching image /home/rveguilla/.minikube/cache/images/mysql_5: open /home/rveguilla/.minikube/cache/images/mysql_5: no such file or directory
```
I got the same error on both macOS and Linux.

**Comment by lzhshen** [comment]
@tstromberg , I met the same issue

f2@zzz-MS-7A94:~/.minikube/cache/images/gcr.io/kubeflow-images-public/katib$ minikube cache add gcr.io/kubeflow-images-public/katib/katib-ui:v0.1.2-alpha-63-g9d59a10 --v=5 --alsologtostderr
I1209 14:27:38.551050    6104 notify.go:121] Checking for updates...
I1209 14:27:40.395382    6104 cache_images.go:279] Attempting to cache image: gcr.io/kubeflow-images-public/katib/katib-ui:v0.1.2-alpha-63-g9d59a10 at /home/f2/.minikube/cache/images/gcr.io/kubeflow-images-public/katib/katib-ui_v0.1.2-alpha-63-g9d59a10
I1209 14:27:40.395427    6104 cache_images.go:82] Successfully cached all images.
I1209 14:27:40.414094    6104 cache_images.go:197] Loading image from cache at  /home/f2/.minikube/cache/images/gcr.io/kubeflow-images-public/katib/katib-ui_v0.1.2-alpha-63-g9d59a10
I1209 14:27:40.414130    6104 ssh_runner.go:57] Run: sudo rm -f /tmp/katib-ui_v0.1.2-alpha-63-g9d59a10
I1209 14:27:40.420397    6104 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I1209 14:27:41.888738    6104 ssh_runner.go:57] Run: docker load -i /tmp/katib-ui_v0.1.2-alpha-63-g9d59a10
Error caching and loading images: loading cached images: loading image /home/f2/.minikube/cache/images/gcr.io/kubeflow-images-public/katib/katib-ui_v0.1.2-alpha-63-g9d59a10: loading docker image: /tmp/katib-ui_v0.1.2-alpha-63-g9d59a10: Process exited with status 1

So I ssh to minikube and run following command:

$ docker load -i /tmp/katib-ui_v0.1.2-alpha-63-g9d59a10
ebf12965380b: Loading layer [==================================================>]  2.107MB/2.107MB
4f2ab6a61f50: Loading layer [==================================================>]     126B/126B
Error processing tar file(exit status 1): operation not supported

**Comment by tstromberg** [comment]
Has anyone run into this with v0.33.1? I'm tempted to close this as obsolete, as these commands are  working for me with Linux/kvm2 and macOS/virtualbox:

`minikube cache add gcr.io/kubeflow-images-public/katib/katib-ui:v0.1.2-alpha-63-g9d59a10 --v=5 --alsologtostderr`
`minikube cache add mysql:5 --v=5 --alsologtostderr`

I suspect there is something environmental, but I'm still not sure what's going on. If you run into this, do you mind sharing the output of `docker -v`? I've tested on 18.06-1-ce and docker-less.

**Comment by tstromberg** [comment]
Closing this bug as it hasn't seen activity in awhile, and it's possible that it has been long fixed.

**Comment by sivareddyforu** [comment]
this issue still present even on v1.18 minikube
eahy-m-57000481:docker user$ minikube cache add my-project --v=5 --alsologtostderr
I0330 16:41:38.305721   27364 cache_images.go:279] Attempting to cache image: my-project at /Users/user/.minikube/cache/images/my-project
I0330 16:41:38.308179   27364 cache_images.go:82] Successfully cached all images.
I0330 16:41:39.677253   27364 cache_images.go:197] Loading image from cache at  /Users/user/.minikube/cache/images/my-project
I0330 16:41:39.677779   27364 ssh_runner.go:57] Run: sudo rm -f /tmp/my-project
I0330 16:41:40.413054   27364 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0330 16:41:41.398375   27364 ssh_runner.go:57] Run: docker load -i /tmp/my-project
Error caching and loading images: loading cached images: loading image /Users/user/.minikube/cache/images/my-project: loading docker image: /tmp/my-project: Process exited with status 1
