### ISSUE TITLE
none: Allow host IP to be settable

### ISSUE THREAD

**Issue by elioengcomp** [kubernetes/minikube#2762]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.26.1
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**: I'm getting a broken cluster everytime my host IP changes. It looks like the Pods keep trying to reach the host using the old IP. I tried to set the host IP by starting minikube with the following command, but it did not work:

```
minikube start --vm-driver=none --apiserver-name=localhost --apiserver-ips=127.0.0.1 --extra-config=kubelet.node-ip=127.0.0.1
```

**What you expected to happen**: I would like to be able to set the host IP to make my minikube installation survive network changes.

**How to reproduce it** (as minimally and precisely as possible): 

1. Start a minikube cluster using `vm-driver=none`
2. Deploy an application to the cluster (It can be the dashboard)
3. Stop minikube
4. Change the host IP address
5. Restart minikube
6. Try to access the application.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by elioengcomp** [comment]
@margh can you provide more details about this? 

My `daemon.json` looks like this:

```
{
    "bip": "172.17.1.0/16"
}
```

**Comment by ToddMorrill** [comment]
Second the above question. I'm struggling to find clear instructions on how to create a bridge network. The closest thing [I can find is this](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/build-bridges/), which doesn't really explain anything or solve the problem.

**Comment by spstarr** [comment]
`--vm-driver=none` isn't just for hosts it can be for VMs already created, which is what I use it for.

Except I'd like to be able to choose what interface or IP to bind the cluster to so I can connect to pods (or do I need flannel).

Right now, I sort of cheat, I use the Docker IP network and route to it from outside the VM, but trying to use Ingress with minikube doesn't work since it won't let me set the IP i want the cluster to be available on (to connect to the pods within the cluster).

**Comment by tstromberg** [comment]
Fixed by https://github.com/intelfx/minikube/commit/7535abe3c4a1851640517409e547a4d94c156c50

**Comment by tstromberg** [comment]
Looks like I may have been mistaken about this being fixed.

**Comment by rodjjo** [comment]
> minikube start --vm-driver=none --apiserver-name=localhost --apiserver-ips=127.0.0.1 --extra-conf=kubelet.node-ip=127.0.0.1

did you mean *--extra-config* not --extra-conf ?

**Comment by elioengcomp** [comment]
I think so. Just fixed it.

**Comment by rodjjo** [comment]
@elioengcomp 

Mabye you can reuse minikube after ip changes by running:

```bash
minikube update-context && sudo systemctl restart kubelet 
```
^ that does not solve the problem but at least you can still using minikube.

**Comment by elioengcomp** [comment]
Thanks for the tip @rodjjo. It has been a while since I was working on this. I will give it a try when I have the chance.

**Comment by tstromberg** [comment]
Closing as there is apparently a workaround.

**Comment by raul1991** [comment]
> Closing as there is apparently a workaround.

and what is that ? Can you copy that again here ?
