### ISSUE TITLE
Minikube v0.28 not starting

### ISSUE THREAD

**Issue by chrisalex2** [kubernetes/minikube#2904]
**Environment**:

**Minikube version**: v0.28.0
- **OS** : Windows 10
- **VM Driver**: hyperv

**What happened**: Starting minikube with v0.28.0 throws the following error: 

E0614 17:09:30.577303    1732 start.go:174] Error starting host:  Error creating host: Error executing step: Provisioning VM.
: Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**What you expected to happen**: minikube to start correctly

**How to reproduce it** (as minimally and precisely as possible):
minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch" --cpus 3 --memory 4096

**Output of `minikube logs` (if applicable)**:
F0614 17:18:44.984795   16020 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Anything else do we need to know**:

I have tried the latest version on two different computers running different versions of Windows 10 and both get the same issue.  If I downgrade to v0.27.0 then it starts up fine.

**Comment by ch-abrandt** [comment]
I'm having the same exact issue on OSX 10.13.5

Same log entry:
F0614 10:19:33.601098   44519 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by ch-abrandt** [comment]
My issue was fixed by upgrading to the latest version of Virtual Box and  removing ~/.minikube, then running minikube start.

**Comment by yokodev** [comment]
Ubuntu 16.04 here, same issue... had to:
 
**1. Upgrade VBox 
2. Delete minikube VM
3. Delete  .minikube**

**Comment by Arnavion** [comment]
I placed the path of a native ssh binary in PATH (ssh.exe of git bash) so that minikube uses that instead of its "native Go" SSH implementation, and I have no problems. Something must be busted with the native Go implementation.

**Comment by F21** [comment]
Same issue as @chrisalex2 on Windows 10 64-bit (April Update with latest update).

```
$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0621 09:58:11.754507    8344 start.go:168] Error starting host: Error creating host: Error executing step: Provisioning VM.
: Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remainTemporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain.

 Retrying.
E0621 09:58:11.761506    8344 start.go:174] Error starting host:  Error creating host: Error executing step: Provisioning VM.
: Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remainTemporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
```
Problem persists after deleting `.minikube` and starting from scratch.

**Comment by srflaxu40** [comment]
Yep, same here.  Workaround?  Can I at least use an older version?

**Comment by F21** [comment]
@srflaxu40 I downgraded to 0.27.1 to get it working in the meantime.

**Comment by ShiningRush** [comment]
@F21 It works for my on win10.

**Comment by ducminhn** [comment]
Yep, downgrade to 0.27 works for me as well.

**Comment by stefanjarina** [comment]
I can also confirm. Had the same error with ssh handshake on
`Windows 10 Pro 1803 (OS build 17134.228) with Hyper-V`

Command used:
`minikube start --vm-driver="hyperv" --memory=4096 --cpus=4 --hyperv-virtual-switch="External" --v=7 --alsologtostderr`
Initial version: 0.28.2
Tried the following (removed .minikube and .kube between the steps):

remove optional windows openssh -> *didn't work*
install openssh via chocolate -> *didn't work*
Downgrading to version 0.27 using the built in ssh go iplmenetation -> *didn't work*
Downgrading to 0.27 using the optional windows openssh -> *didn't work*
Downgrading to 0.27 using the OpenSSH 7.7.2.1 from chocolatey --> **THIS WORKED!**

Seems like there is serious bug in 0.28 version.

**Comment by andrew-dinunzio** [comment]
I found that I can start minikube with 0.28.2 but I need to tinker with various settings and try a couple of times to get it working.
* I need to run it from the same drive as my user profile (C:\)
* I found that if I set the memory to 4096, it fails more often than if I set it to something lower
* When I start it, I keep an eye on the VM from the hyperv manager, and if I ever see the memory jump from what I set it to (like 4096) to something lower (like 796), I can confidently say it will fail so I stop it, delete it, and try again. Sometimes it works the next time. Closing programs seems to help (even though I'm nowhere near max RAM usage)
* If I move networks (switching from Wi-Fi to Ethernet for example), my connection to the cluster breaks - so I need to delete and recreate my cluster whenever I switch (or my comp goes to sleep)

**Comment by ChabaOk** [comment]
In Hyper-V on Windows Server 2016, 
I run this command  > _minikube start --vm-driver hyperv --hyperv-virtual-switch "VirtualSwitch-External"_
And get this error.

Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain

From recommendation in above, I found my version is 0.30 and I have rolled back to 0.27. The problem has resolved.

**Comment by davidovich** [comment]
please see #3195 as this is likely the problem fix.

**Comment by jeetwide** [comment]
> I can also confirm. Had the same error with ssh handshake on
> `Windows 10 Pro 1803 (OS build 17134.228) with Hyper-V`
> 
> Command used:
> `minikube start --vm-driver="hyperv" --memory=4096 --cpus=4 --hyperv-virtual-switch="External" --v=7 --alsologtostderr`
> Initial version: 0.28.2
> Tried the following (removed .minikube and .kube between the steps):
> 
> remove optional windows openssh -> _didn't work_
> install openssh via chocolate -> _didn't work_
> Downgrading to version 0.27 using the built in ssh go iplmenetation -> _didn't work_
> Downgrading to 0.27 using the optional windows openssh -> _didn't work_
> Downgrading to 0.27 using the OpenSSH 7.7.2.1 from chocolatey --> **THIS WORKED!**
> 
> Seems like there is serious bug in 0.28 version.

Hi. Can you please help me how do I downgrade it,. 

I have done following things
>choco uninstall minikube
choco install minikube --version 0.27.0 --allow-downgrade

Any help will be highly appreciated.
