### ISSUE TITLE
DNS not working (or not enabled)?

### ISSUE THREAD

**Issue by shmish111** [kubernetes/minikube#52]
Using localkube, SkyDNS was enabled however it does not seem to be setup on minikube:

```
[ root@curl-131556218-gq56k:/ ]$ nslookup kubernetes.default
Server:    10.1.30.3
Address 1: 10.1.30.3

nslookup: can't resolve 'kubernetes.default'
[ root@curl-131556218-gq56k:/ ]$
```

Is it not enabled? It seems like something that is quite commonly used. Is it a bug or me doing something wrong?

**Comment by shmish111** [comment]
I don't know if this is related but I also can't reach a dns server to resolve external addresses. I can reach the internet, for example docker hub below:

```
[ root@curl-131556218-sd6ql:/ ]$ curl -v https://hub.docker.com/
* Couldn't resolve host 'hub.docker.com'
curl: (6) Couldn't resolve host 'hub.docker.com'
[ root@curl-131556218-sd6ql:/ ]$ curl -v 52.4.27.208
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 52.4.27.208
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://52.4.27.208/
< Connection: close
<
[ root@curl-131556218-sd6ql:/ ]$
```

**Comment by luxas** [comment]
Keep in mind that `localkube` is _really_ experimental (alpha) and will change a lot in the near future.

For me, internal DNS didn't work as well (after we've got rid of weave), but this is something I'm going to fix soon with my refactor

We are going to switch to (@)ArtfulCoder's DNS approach with no etcd or kube2sky, just a pure go impl for Kubernetes DNS.

**Comment by shmish111** [comment]
I've been using localkube quite successfully for the past few weeks, the only problem I had was an issue with configMaps https://github.com/redspread/localkube/pull/61 which was fixed by using minikube. I think I will just have to forget minikube and my configMap requirement for now. Can we leave this issue open for DNS?

**Comment by dlorenc** [comment]
Thanks for the report. We absolutely need to get DNS working.

**Comment by luxas** [comment]
@dlorenc I'm soon done with my refactor, only need the flags to start working. Give me some hours, and I'll upload a WIP

@shmish111 Sorry, I meant that minikube's localkube is experimental, redspread's localkube is supported by them and is stable. The `configMap` issue is an Kubernetes issue with `--containerized`

**Comment by shmish111** [comment]
@luxas the configMap stuff works on minikube right now, is that going to keep working or may it break again until kubernetes fix the issue? Is there a github issue for this that I can follow?

**Comment by luxas** [comment]
Yes, it works right now when run in a VM, and I think we're going to keep it as-is.
But there will probably be a option to run minikube with a container (not a VM), and there the issue will persist until Kubernetes gets it fixed.

**Comment by luxas** [comment]
I think this is fixed now. @dlorenc can you verify?

**Comment by dlorenc** [comment]
Yeah, this should be working now. I just ran these steps from here: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns to verify.

kubectl create -f busybox.yaml
pod "busybox" created

kubectl exec busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      kubernetes.default
Address 1: 10.0.0.1

**Comment by drauschenbach** [comment]
Has this regressed? I'm using minikube v0.7.1 with VirtualBox 5.0.26 and can't resolve `kubernetes.default` using dig from a `debian:wheezy` or `debian:jessie` based container.

**Comment by dlorenc** [comment]
Hey,

I don't think this regressed in general, I can still see DNS entries in my
installation. Could you open a new issue and attach the output of "minikube
logs"?

Dan Lorenc

**Comment by cdrage** [comment]
So I've experienced this issue in https://github.com/kubernetes/minikube/issues/1908 perhaps we can re-open this?
