### ISSUE TITLE
Minikube fails after laptop suspend/resume cycle

### ISSUE THREAD

**Issue by karora** [kubernetes/minikube#532]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):
v0.8.0 + git 3cd29b1111ee48f75f2d436060bc217eac2e5c45

**Environment**:
- **OS**: Debian Sid
- **VM Driver** : kvm
- **Docker version**: 1.11.2
- **Install tools**:
- **Others**:

**What happened**:
I start Minikube, use it all day, then suspend my laptop and go home.  The Minikube cluster is no longer working properly when I am at home, although at least some of the actual pods are still running just fine.

**What you expected to happen**:
I expect everything to survive suspend / resume

**How to reproduce it** (as minimally and precisely as possible):
Start Minikube cluster
Suspend / Resume laptop
$ kubectl get namespaces
The connection to the server 192.168.42.24:8443 was refused - did you specify the right host or port?

**Anything else do we need to know**:

I have an iptables rule in the Minikube VM forwarding to a MongoDB pod, which continues to work just fine through all of this.

Here are the start of the output of `minikube logs` from when it begins to fail (including last good line)

0830 16:50:16.655224    2461 operation_executor.go:740] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/69757511-6e94-11e6-b0cf-0233c90115eb-default-token-ip0od" (spec.Name: "default-token-ip0od") pod "69757511-6e94-11e6-b0cf
-0233c90115eb" (UID: "69757511-6e94-11e6-b0cf-0233c90115eb").
fatal error: concurrent map writes

goroutine 496746 [running]:
runtime.throw(0x290ec3d, 0x15)
        /usr/lib/go-1.7/src/runtime/panic.go:566 +0x95 fp=0xc420b79be0 sp=0xc420b79bc0
runtime.mapassign1(0x2451780, 0xc421621f80, 0xc420b79d58, 0xc420b79d68)
        /usr/lib/go-1.7/src/runtime/hashmap.go:553 +0x2e1 fp=0xc420b79cc8 sp=0xc420b79be0
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc4201c36b0, 0x28e2afa, 0x4, 0x28aac40, 0xc427807b00, 0x1, 0x0)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:314 +0x249 fp=0xc420b79db0 sp=0xc420b79cc8
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Resync(0xc4201c36b0, 0x0, 0x0)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:498 +0x179 fp=0xc420b79e88 sp=0xc420b79db0
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc42495ddf0, 0xc42005aea0, 0xc4213005a0, 0xc4246536e0, 0xc42495ddf8)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:289 +0x1b5 fp=0xc420b79f88 sp=0xc420b79e88
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420b79f90 sp=0xc420b79f88
created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:296 +0x4c0

goroutine 1 [chan receive, 441 minutes]:
k8s.io/minikube/cmd/localkube/cmd.StartLocalkube()
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd/start.go:56 +0x18f
k8s.io/minikube/cmd/localkube/cmd.glob..func1(0x3e39f00, 0xc420285d20, 0x0, 0x2)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd/root.go:31 +0x14
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x3e39f00, 0xc42000c100, 0x2, 0x2, 0x3e39f00, 0xc42000c100)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:565 +0x411
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x3e39f00, 0x4, 0x2967dca, 0x2e)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:651 +0x367
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x3e39f00, 0x0, 0x0)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:610 +0x2b
main.main()
        /home/karora/go/src/k8s.io/minikube/cmd/localkube/main.go:32 +0x5f

goroutine 17 [syscall, 441 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.7/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [chan receive]:
k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x4010de0)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:879 +0x7a
created by k8s.io/minikube/vendor/github.com/golang/glog.init.1
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 16 [syscall, 441 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/go-1.7/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
        /usr/lib/go-1.7/src/os/signal/signal_unix.go:28 +0x41

goroutine 63 [chan receive]:
k8s.io/minikube/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc4201aee20)
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x94
created by k8s.io/minikube/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
        /home/karora/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xd2

**Comment by andrewgdavis** [comment]
This looks to be related to https://github.com/kubernetes/minikube/issues/368

I applied the the PR kubernetes/kubernetes#30948, rebuilt minikube, and the issue has been resolved.

**Comment by dlorenc** [comment]
Thanks for helping debug @andrewgdavis. We're planning to do a release of k8s v1.4-beta3 tomorrow, but it won't be the default. Unfortunately the upstream fix hasn't been cherry picked into any of the 1.3.* releases, so it would be tricky for us to get it in our 1.3 builds. It might be worth us manually applying it though into a 1.3.6 release.

**Comment by dlorenc** [comment]
FYI, we released the v1.4-beta.0 build. You can see it with:

```shell
$ minikube get-k8s-versions
The following Kubernetes versions are available:
        - v1.4.0-beta.0
        - v1.3.6
        - v1.3.5
        - v1.3.4
        - v1.3.3
        - v1.3.0
```

And use it with:
```shell
$ minikube start --kubernetes-version=v1.4-beta.0
```

**Comment by dlorenc** [comment]
This doesn't look like it's getting fixed in earlier k8s builds, so we'll have to close this and move forward.

**Comment by karora** [comment]
```
$ minikube start --cpus 2 --memory 8192 --disk-size 40g --vm-driver kvm --kubernetes-version=v1.4-beta.0
Starting local Kubernetes cluster...
E0912 09:24:09.997064    7471 start.go:108] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: Max error attempts retrying localkube downloader: Error getting localkube download url: Error creating semver version from localkube version input string: Invalid character(s) found in minor number "4-beta"
```

So I guess I'm missing something in that workaround...

**Comment by jimmidyson** [comment]
Try `1.4.0-beta.0` (semver requires patch version).

**Comment by karora** [comment]
Thanks, that gets me further, but localkube still does not start in the VM.  This is an inconvenience, not a roadblock, so I'll just wait for 1.4.0 to get released - looks like it should arrive sometime in the next fortnight :-)

Thanks for your help.

**Comment by jimmidyson** [comment]
Can you share `minikube logs` so we can figure out why it doesn't start please?

**Comment by karora** [comment]
It seems perhaps the command-line flags for localkube have changed:
```
$ minikube logs
==> /var/lib/localkube/localkube.err <==

==> /var/lib/localkube/localkube.out <==
unknown flag: --node-ip
Usage of /usr/local/bin/localkube:
 ...
```

Am I doing something wrong?  The localkube that I built when I built this minikube does have the --node-ip option - just that the one downloaded as part of the 1.4.0-beta.0 doesn't seem to have it.  In the past I've always ignored the localkube that was built along with minikube.

**Comment by jimmidyson** [comment]
Ah looks like this fix should have been cherry-picked into the 1.4 branch too. The fix is important to make sure the node IP returned from API is a routeable address across virt providers.

**Comment by dlorenc** [comment]
Ah yeah, we'll need to get this flag into the 1.4 branch. We should probably rebuild most of the localkube changes with it.

My git cherry-pick skills are pretty weak :) Any advice on how to get this into the 1.4 branch, before all the existing 1.4 builds?

Ref #512

**Comment by dlorenc** [comment]
I guess I could just rebase the entire 1.4 branch onto master. We'll get other changes too, but I don't think there was anything we don't want.
