### ISSUE TITLE
Starting minikube without docker requires... docker

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5549]
There is something wrong in the runtime detection of the precreate:

```console
$ sudo minikube start --vm-driver=none --container-runtime=cri-o
😄  minikube v1.4.0 on Ubuntu 16.04
🤹  Running on localhost (CPUs=4, Memory=7800MB, Disk=138379MB) ...
🔄  Retriable failure: create: precreate: exec: "docker": executable file not found in $PATH
```

For some reason it is calling the wrong `Available` function ?

```go
func (r *Docker) Available() error {
	_, err := exec.LookPath("docker")
	return err
}
```

```go
func (r *CRIO) Available() error {
	return r.Runner.Run("command -v crio")
}
```
And the docker runtime seems to be checking _locally_ ?
(I guess us using docker machine makes it always there)

It also forgot to look for `crictl`, but that is another story.

**Comment by afbjorklund** [comment]
Interestingly, we are calling NewDriver **twice**. Once with correct values, once with empty ones:

```
I1006 18:22:15.786795   11858 none.go:67] none: {minikube /home/anders/.minikube cri-o}
I1006 18:22:15.786826   11858 cruntime.go:89] cruntime: {cri-o  0x3027db0  }
I1006 18:22:15.786953   11858 none.go:67] none: {  }
I1006 18:22:15.786973   11858 cruntime.go:89] cruntime: {  0x3027db0  }
```

This is how we end up with `Docker` for the runtime, even though it was supposed to be `CRIO`.

```go
	case "", "docker":
		return &Docker{Socket: c.Socket, Runner: c.Runner}, nil
	case "crio", "cri-o":
		return &CRIO{Socket: c.Socket, Runner: c.Runner, ImageRepository: c.ImageRepository, KubernetesVersion: c.KubernetesVersion}, nil
```

**Comment by afbjorklund** [comment]
Unfortunately this suggests that something is fundamentally wrong in the Driver "registry" ?

First the config is happily created by "createNoneHost", only to get clobbered by "init"'s empty

**Comment by afbjorklund** [comment]
Hopefully else understands how the "registry" is supposed to work, and can fix this ?

An interesting story on RHEL 8 is that installing `podman-docker` makes it segfault instead.
Mostly due to the "unexpected" advertisement on stdout, about docker compatibility issues:

```console
# docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:       1.0.5
Go Version:    go1.11.6
OS/Arch:       linux/amd64
```

**Comment by Skybladev2** [comment]
I see this error when deleting and starting minikube cluster again (no args).
How to fix this?

**Comment by afbjorklund** [comment]
Well, the workaround is to make something/anything called "docker" available.
But the real fix means improving the minikube driver registry, which is broken...

**Comment by afbjorklund** [comment]
Still broken, in 1.8.1.

```
💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: precreate: exec: "docker": executable file not found in $PATH

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

/remove-lifecycle stale

**Comment by mazzystr** [comment]
`$ sudo minikube start --vm-driver=none --container-runtime=cri-o` works for me on Fedora 31.  I am also reverted to cgroups v1 per docker [procedure](https://docs.docker.com/engine/install/fedora/).

```
minikube start --container-runtime=cri-o --network-plugin=cni --enable-default-cni --driver=none --alsologtostderr --v=5
....
blah
🏄  Done! kubectl is now configured to use "minikube"
I0424 14:47:29.871172  533397 start.go:454] kubectl: 1.18.1, cluster: 1.18.0 (minor skew: 0)
```
```
# kubectl get nodes
NAME    STATUS   ROLES    AGE     VERSION
cube0   Ready    master   5m16s   v1.18.0
```
```
# docker version
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Version:            1.9.0
RemoteAPI Version:  1
Go Version:         go1.13.9
OS/Arch:            linux/amd64
```

**Comment by afbjorklund** [comment]
Nice that the workaround works, but user should _not_ have to install `podman-docker` emulator.

**Comment by x7upLime** [comment]
This issue has to do with how the none driver is designed,
relative to how createHost[pkg/minikube/machine/start.go] is designed:
```

func createHost(api libmachine.API, cfg *config.ClusterConfig, n *config.Node) (*host.Host, error) {
       // inside this function we have access to the cluster config.
       // ....
	def := registry.Driver(cfg.Driver)
       // ....
	dd, err := def.Config(*cfg, *n)
       // ....
	data, err := json.Marshal(dd)
       // ....

	h, err := api.NewHost(cfg.Driver, data)
       // ...
	if err := timedCreateHost(h, api, cfg.StartHostTimeout); err != nil {
      // .....

```
timedCreateHost() in turn, calls api.Create, passing the *host.Host, which contains the driver we've *initialized" inside api.NewHost.

The thing is that NewHost (which doesn't have access to the cluster config) does this annoying thing:

```
	1. def := registry.Driver(drvName)
	2. d := def.Init()
	3. err := json.Unmarshal(rawDriver, d)
	   where rawDriver is the local name for the passed 'data'
```
After the json.Unmarshal, that's the driver we're ending with.



That's how the none driver looks like:
```
type Driver struct {
	*drivers.BaseDriver
	*pkgdrivers.CommonDriver
	URL     string
	runtime cruntime.Manager
	exec    command.Runner
}
```
it relies on runtime and exec, which have to be initialized,
but nothing that is to be initialized would pass the marshal/unmarshal thing in api.NewHost.

So what is happening is that when def.Init() is called inside api.NewHost:

```
// pkg/minikube/registry/drvs/none/none.go
		Init:     func() drivers.Driver { return none.NewDriver(none.Config{}) },
```

a none.NewDriver call is issued, with an empty none.Config.. 
```
func NewDriver(c Config) *Driver {
	runtime, err := cruntime.New(cruntime.Config{Type: c.ContainerRuntime, Runner: runner})
        // ...
	return &Driver{
               // ...
		runtime: runtime,
	}
}

```
(makes sense, 'cause we shouldn't know anything about the driver during initialization.. that's what config should be for)

So that we're initializing a cruntime with ac.ContainerRuntime == "",
which defaults to docker:  `case "", "docker":`, inside pkg/minikube/cruntime/cruntime.go
So no container-runtime config should work with the none driver during this step.

And after our unmarshal... 
(raw json looking like this:
```
"{\"IPAddress\":\"\",\"MachineName\":\"minikube\",\"SSHUser\":\"\",\"SSHPort\":0,\"SSHKeyPath\":\"\",\"StorePath\":\"/home/ubuntu/.minikube\",\"SwarmMaster\":false,\"SwarmHost\":\"\",\"SwarmDiscovery\":\"\",\"URL\":\"\"}"
```
..the runtime field of the struct is not even exported, so there is no way even for the runtime config to be passed on.)

the runtime remains docker.

**Comment by x7upLime** [comment]
The other drivers doesn't seem to have this issue: none of them seems to rely on initialized stuff after config.
- qemu -- it doesn't have anything that has to be initialized inside the Driver struct
- kvm -- same
- hyperkit -- same
- kic -- it keeps the config passed to NewDriver, inside the driver itself.. and does its "initialization", directly inside (*Driver).Create()

Only hyperkit does an explicit (*Driver).PrecreateCheck()

**Comment by afbjorklund** [comment]
Thanks for figuring out the registry bug, it was somewhat puzzling.

For reference, the upstream driver looks like this:

```go
func NewDriver(hostName, storePath string) *Driver {
        return &Driver{
                BaseDriver: &drivers.BaseDriver{
                        MachineName: hostName,
                        StorePath:   storePath,
                },
        }
}
```

With your changes, the none2 is more similar to it.

**Comment by afbjorklund** [comment]
This would probably fix some similar issues, with the "ssh" driver

**Comment by divysinghvi** [comment]
@afbjorklund Hey is this issue resolved or currently being worked on? or  could be closed

**Comment by afbjorklund** [comment]
I think it was fixed eventually, should be easy to confirm or deny with an empty VM (not having `docker`)?

**Comment by divysinghvi** [comment]
awesome i will try duplicating it and if it's fixed then we can close it thanks

**Comment by afbjorklund** [comment]
It was still an issue, when we tried to replace Katacoda (we made a workaround with a fake `docker`)

https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/

**Comment by afbjorklund** [comment]
It is still broken, in 1.37.0:

`✨  Using the none driver based on user configuration`
`❗  Using the 'containerd' runtime with the 'none' driver is an untested configuration!`

`🤦  StartHost failed, but will try again: creating host: create: precreate: exec: "docker": executable file not found in $PATH`
`😿  Failed to start none bare metal machine. Running "minikube delete" may fix it: creating host: create: precreate: exec: "docker": executable file not found in $PATH`

There were some attempts to fix the broken minikube registry in 2023, but they were never finished:

* https://github.com/kubernetes/minikube/pull/15736

**Comment by divysinghvi** [comment]
thanks @afbjorklund  for confirming , Then this issue still needs to be worked on will keep this in mind to bring up future office hours regarding what could be done
