### ISSUE TITLE
hyperkit: new host: dial-http tcp 127.0.0.1:x: unexpected EOF

### ISSUE THREAD

**Issue by vorpleblade** [kubernetes/minikube#5571]
**The exact command to reproduce the issue**:
minikube start --vm-driver=hyperkit

**The full output of the command that failed**:<details>

minikube start --vm-driver=hyperkit
😄  minikube v1.4.0 on Darwin 10.14.6
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:51698: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:51704: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:51709: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:51715: unexpected EOF

💣  Unable to start VM: new host: dial-http tcp 127.0.0.1:51715: unexpected EOF

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

---
hyperkit -v
hyperkit: v0.20190201-11-gc0dd46

Homepage: https://github.com/docker/hyperkit
License: BSD

</details>

**The output of the `minikube logs` command**:<details>

minikube logs

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
System Version: macOS 10.14.6 (18G103)
Kernel Version: Darwin 18.7.0

**Comment by tstromberg** [comment]
Sorry to hear that this isn't working - I've not seen this message before. Do you mind sharing the output of:

`minikube start --alsologtostderr -v=8`

Is it possible there is a firewall that may be blocking the connection?

**Comment by vorpleblade** [comment]
Output of `minikube start --alsologtostderr -v=8 >> output.log 2>&1` attached
[output.log](https://github.com/kubernetes/minikube/files/3709679/output.log)

**Comment by tstromberg** [comment]
@vorpleblade - My guess is that the hyperkit driver is crashing, possibly segfaulting.

Do you mind trying with minikube v1.5.0-beta.0? It's unlikely to fix the problem, but we fixed an issue with libmachine logging that was blocking our ability to tell what was going on here.

https://github.com/kubernetes/minikube/releases/tag/v1.5.0-beta.0

**Comment by vorpleblade** [comment]
@tstromberg Attached is the output for version 1.5.0
[1.5.0.output.log](https://github.com/kubernetes/minikube/files/3785481/1.5.0.output.log)

**Comment by medyagh** [comment]
@vorpleblade  do you mind sharing your hyperkit version ?
```
hyperkit -v
```


@vorpleblade I wonder if upgrading hypkerkit would help you as it did in this issue ?
https://github.com/kubernetes/minikube/issues/5594

**Comment by vorpleblade** [comment]
@medyagh Still failing.  I uninstalled minikube and deleted the ~/.minikube directory then reinstalled minikube

minikube version
```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad
```
hyperkit version
```
hyperkit: v0.20190201-11-gc0dd46

Homepage: https://github.com/docker/hyperkit
License: BSD
```

docker version
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

output from `minikube start --alsologtostderr -v=8 >> output.log 2>&1`
[output.log](https://github.com/kubernetes/minikube/files/3809731/output.log)

**Comment by tstromberg** [comment]
Do you mind running the following to check what may be going on with the driver on this host?

`(env MACHINE_PLUGIN_TOKEN=42 ~/.minikube/bin/docker-machine-driver-hyperkit; echo $? >2) &`

It will quickly output an 127.0.0.1:<random port> before shutting down 10 seconds later. Do you mind showing the output of the above command, and the output of this command:

`curl --http2 http://127.0.0.1:<random port>`

My current take is that either the driver is hitting a panic, or more likely, a local process (firewall or Little Snitch) is interfering with the ability for minikube to connect to the local service. I expect that curl will return a 404.

**Comment by vorpleblade** [comment]
@tstromberg I was hoping that it did not return the expected value. :(

```
$ (env MACHINE_PLUGIN_TOKEN=42 ~/.minikube/bin/docker-machine-driver-hyperkit; echo $? >2) &
[1] 31814
127.0.0.1:60441
$ 
[1]+  Done                    ( env MACHINE_PLUGIN_TOKEN=42 ~/.minikube/bin/docker-machine-driver-hyperkit; echo $? > 2 )
$ 
```

```
$ curl --http2 http://127.0.0.1:60441
404 page not found
```

**Comment by tstromberg** [comment]
If curl can access the endpoint, but minikube cannot, perhaps minikube is being denied by an application firewall? Do you have Little Snitch, Radio Silence, or some other network monitor/blocking program installed?

Another possibility is that the driver is quietly crashing in a way that curl doesn't trigger.

Do you mind opening `/Applications/Utilities/Console` and see if any interesting messages pop up when you startup minikube? I would also like to see the output of this command after minikube displays the error:

`find ~/Library/Logs/ -mmin -1`

I'm quietly hoping to see something added to `~/Library/Logs/DiagnosticReports/`, which shows up in Console under "User Reports".

Thank you for your help in unearthing this baffling mystery.

**Comment by vorpleblade** [comment]
@tstromberg Thank you for your help and troubleshooting ideas.  I'm thinking this is some type of timeout issue.  I have not seen any output from `find ~/Library/Logs/ -mmin -1`

However, after several attempts to collect any debug info I finally got this output.
```

$ minikube start
🙄  minikube v1.5.2 on Darwin 10.14.6
✨  Automatically selected the 'hyperkit' driver
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:60341: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:60371: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: new host: dial-http tcp 127.0.0.1:60394: unexpected EOF
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
🚜  Pulling images ...
❌  Unable to pull images, which may be OK: running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": Process exited with status 1
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
⚠️  /usr/local/bin/kubectl is version 1.14.7, and is incompatible with Kubernetes 1.16.2. You will need to update /usr/local/bin/kubectl or use 'minikube kubectl' to connect with this cluster
$ 
```

```
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   4m15s
$ 
```

Trying to execute the hello-minikube pod has the status of **ImagePullBackOff**.
```
$ kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10
deployment.apps/hello-minikube created
$ kubectl expose deployment hello-minikube --type=NodePort --port=8080
service/hello-minikube exposed
$ kubectl get pods
NAME                              READY   STATUS             RESTARTS   AGE
hello-minikube-797f975945-zqd6n   0/1     ImagePullBackOff   0          2m24s
$
```
Getting pod details ...
```
$ kubectl describe pod hello-minikube-797f975945-zqd6n
Name:               hello-minikube-797f975945-zqd6n
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               minikube/192.168.64.7
Start Time:         Thu, 07 Nov 2019 19:36:07 -0600
Labels:             app=hello-minikube
                    pod-template-hash=797f975945
Annotations:        <none>
Status:             Pending
IP:                 172.17.0.4
Controlled By:      ReplicaSet/hello-minikube-797f975945
Containers:
  echoserver:
    Container ID:   
    Image:          k8s.gcr.io/echoserver:1.10
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pkkqp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-pkkqp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pkkqp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  <unknown>            default-scheduler  Successfully assigned default/hello-minikube-797f975945-zqd6n to minikube
  Normal   Pulling    66s (x4 over 3m19s)  kubelet, minikube  Pulling image "k8s.gcr.io/echoserver:1.10"
  Warning  Failed     51s (x4 over 3m1s)   kubelet, minikube  Failed to pull image "k8s.gcr.io/echoserver:1.10": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Failed     51s (x4 over 3m1s)   kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    39s (x6 over 3m)     kubelet, minikube  Back-off pulling image "k8s.gcr.io/echoserver:1.10"
  Warning  Failed     26s (x7 over 3m)     kubelet, minikube  Error: ImagePullBackOff
$ 
```

**Comment by Chris-Ju** [comment]
@vorpleblade Hello, I have the same problem now, Could you tell me how to solve it? Thanks..

**Comment by tstromberg** [comment]
> ```
> ⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
```

This is a bad sign: minikube can't access the Kubernetes container website. I suspect a firewall may be blocking it from access.


```
"k8s.gcr.io/echoserver:1.10": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

This too is a bad sign: not only is minikube being denied access to the internet, but your hyperkit VM is as well. I would encourage you to take a look at whatever firewalling configuration you may have on this system.

Do you mind confirming whether this works:

`curl -vv http://k8s.gcr.io/`

**Comment by priyawadhwa** [comment]
Hey @vorpleblade are you still seeing this issue? If so, could you provide the ouptut of:

```
curl -vv http://k8s.gcr.io/
```

Thank you!

**Comment by medyagh** [comment]
@vorpleblade  I haven't heard from you I will close this issue, please feel free to reopen
I also suggest to try our new driver docker, 
```
minikube start --vm-driver=docker
```

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
