### ISSUE TITLE
When offline, minikube commands give errors

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#652]
looks like when you don't have internet connectivity, minikube gives an error:

```
$ minikube status
E1004 11:16:01.346679   83344 notify.go:55] Error getting json from minikube version url: Error getting minikube version url via http: Get https://storage.googleapis.com/minikube/releases.json: dial tcp: lookup storage.googleapis.com on 8.8.4.4:53: read udp 172.20.74.176:61113->8.8.4.4:53: i/o timeout
```

Would be nice to clean that up

**Comment by arun-gupta** [comment]
Observed the same error earlier during my flight as well, would be good to clean this up.

**Comment by r2d4** [comment]
You can add a WantUpdateNotification: false in `~/.minikube/config/config.json`

We should add this to the README and probably to that error message. In the next release you should just be able to set it through `minikube config set WantUpdateNotification false`

**Comment by sebgoa** [comment]
strange, but that file does not exist on my installation. v0.10.0

**Comment by r2d4** [comment]
You may need to create it if it isn't there.

**Comment by r2d4** [comment]
Closing this, please reopen if you're still having trouble!

**Comment by sebgoa** [comment]
I am not having trouble, I am just reporting an error message that is confusing.
it does not affect the functionality of minikube.

I think that:

1-the ~/.minikube/config/config.json should be created by default
2-`minikube config` should have a `view` subcommand like kubectl 
3-the variables should be well documented.

**Comment by sebgoa** [comment]
and if I try to set the variable you mention 👍 

```
$ minikube version
minikube version: v0.10.0
sebair: kompose (master)$ minikube config set WantUpdateNotification false
Property name WantUpdateNotification not found
```

**Comment by arun-gupta** [comment]
Downloaded minikube 1.4, `minikube start` gives the following message:

```
minikube start
E1008 10:09:38.728676   18372 notify.go:54] Error getting json from minikube version url: Error getting minikube version url via http: Get https://storage.googleapis.com/minikube/releases.json: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:65514->[::1]:53: read: connection refused
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
```

There is no option to reopen the bug.

**Comment by r2d4** [comment]
Support for that command was just released in v0.11.0.  I agree that we should probably document them better - we can add something to the README also.

The available commands for config should also be viewable with `minikube config -h` in v0.11.0

I've reopened it for you.

**Comment by sebgoa** [comment]
So to clarify how I think this should be fixed.

We should be able to have 'WantUpdateNotification' set to true no matter what, but minikube should be able to check if it has network or not. If there is no network connectivity possible then minikube should print a warning instead of an error. With a message like:

`We cannot contact Blah, to be determine possible updates`

It seems weird to have to toggle the setting in the config, to be able to suppress an error message depending on our network environment.

**Comment by r2d4** [comment]
`minikube config view` was merged in this PR https://github.com/kubernetes/minikube/pull/695

**Comment by rafaelsoaresbr** [comment]
This message appear every time I open the Terminal without internet connection after adding `source <(minikube completion bash)` to my `~/.bashrc` file. What about adding this to `~./profile` instead? Would I receive update notifications this way?

**Comment by lizrice** [comment]
I've been having a similar problem trying to start minikube offline.  I got past the "Error getting json from minikube version url" error by setting WantUpdateNotifications to false as described here, but I'm still unable to progress due to another similar error: Error getting valid Kubernetes versions Error getting the localkube versions: Error getting json via http with url: https://storage.googleapis.com/minikube/k8s_releases.json

**Comment by CodeJjang** [comment]
Any luck running minikube from scratch in an offline environment?

**Comment by Sri-Sonti** [comment]
Observing the same error '  Error getting json from url: https://storage.googleapis.com/minikube/k8s_releases.json via http: Get https://storage.googleapis.com/minikube/k8s_releases.json: dial tcp [2a00:1450:4009:807::2010]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.'   This error is observed when setting up minikube on windows . This remains same either with internet proxy or offline .

**Comment by yezhengli-Mr9** [comment]
> Downloaded minikube 1.4, `minikube start` gives the following message:
> 
> ```
> minikube start
> E1008 10:09:38.728676   18372 notify.go:54] Error getting json from minikube version url: Error getting minikube version url via http: Get https://storage.googleapis.com/minikube/releases.json: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:65514->[::1]:53: read: connection refused
> Starting local Kubernetes cluster...
> Kubectl is now configured to use the cluster.
> ```
> 
> There is no option to reopen the bug.

How to resolve this? Happened on two Ubuntu 22.04:
```bash
 minikube start
E0306 10:47:31.719042   14458 notify.go:54] Get https://storage.googleapis.com/minikube/releases.json: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable
Starting local Kubernetes cluster...
E0306 10:47:31.721271   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:818::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.723040   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.724766   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:82e::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.724777   14458 start.go:89] Error starting host:  Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:818::201b]:443: connect: network is unreachable
Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable
Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:82e::201b]:443: connect: network is unreachable

```
