### ISSUE TITLE
Unable to start minikube on AWS Cloud9 Ubuntu

### ISSUE THREAD

**Issue by r-suresh-kumar** [kubernetes/minikube#8228]
**Steps to reproduce the issue:** 

1. minikube start --driver=docker --base-image=gcr.io/k8s-minikube/kicbase:v0.0.10
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

jenkins-capstone:~/environment $ minikube start --driver=docker --base-image=gcr.io/k8s-minikube/kicbase:v0.0.10
😄  minikube v1.10.1 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0521 06:04:05.368542   23118 cache.go:129] Error downloading kic artifacts:  getting remote image: GET https://docker.pkg.github.com/v2/kubernetes/minikube/kicbase/manifests/v0.0.10: UNAUTHORIZED: GitHub Docker Registry needs login
🤷  docker "minikube" container is missing, will recreate.
E0521 06:04:05.583468   23118 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: unauthorized: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
See 'docker run --help'.

🤷  docker "minikube" container is missing, will recreate.
E0521 06:04:35.988858   23118 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. "minikube start" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: unauthorized: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
See 'docker run --help'.

💣  error provisioning host: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: unauthorized: Your token has not been granted the required scopes to execute this query. The 'name' field requires one of the following scopes: ['read:packages'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
See 'docker run --help'.

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by r-suresh-kumar** [comment]
I have been facing this issue for about a week and could not fix it by any means....
Could you please check if this is really an issue / or my oversight in any execution of any commands

Thanks

**Comment by r-suresh-kumar** [comment]
I have logged into Docker and Github before execution of this command
- docker login
- docker login docker.pkg.github.com

**Comment by r-suresh-kumar** [comment]
After multiple reboots and re-trials, I am able to see the following

😄  minikube v1.10.1 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
❌  Unable to load cached images: loading cached images: stat /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory

❌  [KUBERNETES_VERSION_MISSING_V] Failed to update cluster updating node: generating kubeadm cfg: parsing Kubernetes version: strconv.ParseUint: parsing "": invalid syntax
💡  Suggestion: Check that your --kubernetes-version has a leading 'v'. For example: 'v1.1.14'

Any help to resolve this error?

Thanks a lot

**Comment by afbjorklund** [comment]
It seems that your docker installation has a problem getting `gcr.io/k8s-minikube/kicbase:v0.0.10`

Alternatives means of getting this image (besides gcr.io and github packages) is being worked on.

> I have been facing this issue for about a week and could not fix it by any means....

You might also want to try one of the _supported_ platforms, before this cloud ?

> I have logged into Docker and Github before execution of this command

It doesn't seem like the `docker login` is making it into the minikube docker.

**Comment by afbjorklund** [comment]
What happens when you do `docker pull gcr.io/k8s-minikube/kicbase:v0.0.10` ?

Is that being blocked somehow ? (from the above log, we only see the fallback)

**Comment by r-suresh-kumar** [comment]
Thank you for the great support

Following is the log observed for docker pull

v0.0.10: Pulling from k8s-minikube/kicbase
Digest: sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438
Status: Image is up to date for gcr.io/k8s-minikube/kicbase:v0.0.10
gcr.io/k8s-minikube/kicbase:v0.0.10

**Comment by afbjorklund** [comment]
Hmm, don't see why it would go to github then... Can you delete and start again ?

Skip the extra base image flag (`--base-image`) and just go with `minikube start`

**Comment by afbjorklund** [comment]
This is a known bug, we will try to have fix out:

` Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"`

It's due to some issues with `docker inspect`

See #8192

**Comment by r-suresh-kumar** [comment]
I have noticed the following.

On deletion:

🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /home/ubuntu/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.

On minikube start:

😄  minikube v1.10.1 on Ubuntu 18.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...

🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

It worked :) 

Thanks a lot...much appreciate your quick turn-around

**Comment by amefonaffia** [comment]
hi @r-suresh-kumar, I am having this same issue still.
In your "On deletion" comment, what do you mean by "Deleting "minikube" in docker ..."?
